!--------------------------------------------------------------------------------------
!
!   NEMOH2 - second order (QTF) - November 2014
!   Contributors list:
!    - Fabien Robaux (EDF/INNOSEA)
!    - G.DELHOMMEAU, THESE DE CHEN XIAO-BO(1988)    
!    - Adrien Combourieu, INNOSEA (adrien.combourieu@innosea.fr)
!--------------------------------------------------------------------------------------

    
    
	PROGRAM HASFSCALC
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    !!!!! CE PROGRAMME CALCULE L INTEGRALE SUR LA SURFACE LIBRE EXACTE DES QTFS     !!!!!!!!!
    !!!!! (POUR L'INSTANT SEULEMENT DE DIFFERENCES). IL UTILISE LES NOTATIONS DE    !!!!!!!!!
    !!!!!  CHEN ET CELLES DANS LE RAPPORT DE STAGE DE FABIEN ROBAUX                 !!!!!!!!!
    !!!!! IL SE PLACE APRES HASFS QUI CALCULE LES QUANTITES SUR LES FACETTES        !!!!!!!!!
    !!!!! (POTENTIELS, VITESSES) ET EFFECTUE LES CALCULS DE CES QUANTITES           !!!!!!!!!
    !!!!! IL IMPORTE DONC POTENTIEL_SL ET EFFECTUE LES CALCULS GRACE A CECI         !!!!!!!!!
    !!!!!                                                                           !!!!!!!!!
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	USE PARA
        IMPLICIT NONE
        INTEGER NSYM,NFAC,NFFL,NDEB,NFIN
        REAL RHO,XCDG,YCDG,ZCDG,TPER,BETA
        COMMON NSYM,NFAC,NFFL,RHO,XCDG,YCDG,ZCDG,TPER,BETA,NDEB,NFIN
        INTEGER,DIMENSION(2*NFA) :: IND
        REAL FSP(NFA),FSM(NFA),TABW(NFA)
        COMMON FSP,FSM,TABW
        REAL XSL(NFASL),YSL(NFASL)
        INTEGER M1SLF(NFASL),M2SLF(NFASL),M3SLF(NFASL),M4SLF(NFASL)
        INTEGER M1SLC(NFASL),M2SLC(NFASL)
        REAL,DIMENSION(6,6,LN):: AIN,ASH
        REAL,DIMENSION(6*LN,6*LN):: AMOR,RAID
        REAL,DIMENSION(2,NFA):: DNSRADR,DNSRADM  !DENSITE DE SOURCE RADIE
        REAL,DIMENSION(2,NFA):: DNSPERR,DNSPERM  !DENSITE DE SOURCE PERTURBE
        COMPLEX,DIMENSION(2,2,NFA):: DNSRADC !DENSITE DE SOURCE RADIE(PULSATION,?,FACETTE) COMPLXE
        COMPLEX,DIMENSION(2,2,NFA):: DNSPERC !DENSITE DE SOURCE PERTURBE(PULSATION,?,FACETTE) COMPLXE
        REAL CN(NFA2,6),CNSLC(3,NFASL)
        INTEGER NT(501),LK(5)
        REAL XR,XZ,APD1X,APD1Z,APD2X,APD2Z
        COMMON/FIC/XR(328),XZ(46),APD1X(328,46),APD1Z(328,46),APD2X(328,46),APD2Z(328,46)
        ! COMPLEX,DIMENSION(328,46)::APDXC,APDZC
        LOGICAL :: FICHEY,ISXYZIN,ISIN
        REAL :: PTPROCHE(2)
        REAL BP,THETA
        COMMON/BP1/BP
        CHARACTER(10) :: IDEN, ID
        CHARACTER(16) :: NOMF4!,NOMF2,NOMF1!,NOMF3!,NOMF5!,NOMF6
        CHARACTER(16) :: NOMB1,NOMB2,NOMB3,NOMB4,NOMB5
        CHARACTER(16) :: NOMH0,NOMH1,NOMH2,NOMH3,NOMH4,NOMH5
        CHARACTER(16) :: NOMGRUN
        REAL X(NPT),Y(NPT),Z(NPT)&
        &,P(NFA),Q(NFA),R(NFA)&
        &,XM(2*NFA),YM(2*NFA),ZM(2*NFA),AIRE(NFA),TDIS(NFA)&
        &,KK(5),AIND(NI),DIST(NFA)
        INTEGER IPOS(LN),IMXC(LN),M3(NFA),M4(NFA),M1(NFA),M2(NFA)
        COMMON/MAIL/ X,Y,Z,M1,M2&
        &,M3,M4,P,Q,R&
        &,XM,YM,ZM,AIRE,TDIS&
        &,IPOS,IMXC,KK,AIND,DIST
        REAL XMSLF(NFASL),YMSLF(NFASL),AIRESLF(NFASL)
        REAL XMSLC(NFASL),YMSLC(NFASL),AIRESLC(NFASL)
        REAL XMSLL(NFASL),YMSLL(NFASL),AIRESLL(NFASL)
        COMMON/DON2/ XMSLF,YMSLF,AIRESLF,XMSLC,YMSLC,AIRESLC,XMSLL,YMSLL,AIRESLL
        REAL VSXP1(NFA),VSYP1(NFA),VSZP1(NFA)&
     &   ,VSXM1(NFA),VSYM1(NFA),VSZM1(NFA)&
     &   ,VSXP2(NFA),VSYP2(NFA),VSZP2(NFA)&
      &  ,VSXM2(NFA),VSYM2(NFA),VSZM2(NFA)&
     &   ,SP1(NFA),SM1(NFA),SP2(NFA),SM2(NFA)
        COMMON/SOU/VSXP1,VSYP1,VSZP1&
     &   ,VSXM1,VSYM1,VSZM1&
     &   ,VSXP2,VSYP2,VSZP2&
      &  ,VSXM2,VSYM2,VSZM2&
     &   ,SP1,SM1,SP2,SM2&
      &  ,NOMF4
        COMPLEX,DIMENSION(:,:,:),ALLOCATABLE :: S1M,S2M,S3M,S4M,S5M,S6M,S7M,E1M,E2M,E3M,E4M
        COMPLEX,DIMENSION(:,:,:),ALLOCATABLE :: S1P,S2P,S3P,S4P,S5P,S6P,S7P,E1P,E2P,E3P,E4P
	COMPLEX, DIMENSION(:,:,:), ALLOCATABLE ::S1BM,S1BP,S4BM,S4BP,E1BM,E1BP
        REAL POT1,POT2,VXB1,VXB2,VYB1,VYB2,VZB1,VZB2
        COMMON/OUTVSBK/POT1,POT2,VXB1,VXB2,VYB1,VYB2,VZB1,VZB2
        COMPLEX, DIMENSION(:,:,:), ALLOCATABLE ::POTINCSLF,POTTOTSLF,POTPERSLF,POTINCSLC,POTTOTSLC,POTPERSLC,POTINCSLL,POTTOTSLL,POTPERSLL
        COMPLEX, DIMENSION(:,:,:,:), ALLOCATABLE ::POTRADSLF,POTRADSLC,POTRADSLL,EFFVERIF,EFFVERIF4,EFFVERIF2,EFFVERIFR2,EFFVERIFB,EFFM,EFFP
        COMPLEX, DIMENSION(:,:,:,:), ALLOCATABLE ::VINCSLF,VTOTSLF,VPERSLF,VINCSLC,VTOTSLC,VPERSLC,VINCSLL,VTOTSLL,VPERSLL
        COMPLEX, DIMENSION(:,:,:,:,:), ALLOCATABLE ::VRADSLF,VRADSLC,VRADSLL
        COMPLEX, DIMENSION(:,:), ALLOCATABLE::S1C,S2C,S3C,S1CB,S4C
        COMMON/VSB/IDEN
        REAL XEFF,YEFF,ZEFF,GM,&
      &  H,PI4,DPI,QPI,NEXP
        INTEGER NC,NCO,NSYMY,NJJ,NP,IMX,IXX,Louthasfs
        COMMON/CST/NC,NCO,NSYMY,NJJ,NP,IMX,IXX,XEFF,YEFF,ZEFF,GM,&
      &  H,PI4,DPI,QPI,NEXP
        REAL::S1BPER(NFA),S1SPER(NFA),S2BPER(NFA),S2SPER(NFA)
        REAL::S1BRAD(NFA),S1SRAD(NFA),S2BRAD(NFA),S2SRAD(NFA)
        REAL::MULTSYM(6)
        CHARACTER*50 FMTV,FMT1,FMT2
	CHARACTER*800 STRFMT
        INTEGER :: FICH,FICH2, lID
        COMPLEX,DIMENSION(1:6,1:6,1:NFA,1:NFA)::CONTRIBM,CONTRIBP
        COMPLEX::PHI1,PHIP1,PHII1,PHI2,PHIP2,PHII2,&
        &PHI1_X,PHIP1_X,PHII1_X,&
        &PHI1_Y,PHIP1_Y,PHII1_Y,&
        &PHI1_Z,PHIP1_Z,PHII1_Z,&
        &PHI1_ZZ,PHIP1_ZZ,PHII1_ZZ,&
        &PHI2_X,PHIP2_X,PHII2_X,&
        &PHI2_Y,PHIP2_Y,PHII2_Y,&
        &PHI2_Z,PHIP2_Z,PHII2_Z,&
        &PHI2_ZZ,PHIP2_ZZ,PHII2_ZZ,&
        &PSIM(6),PSIM_X(6),PSIM_Y(6),PSIM_Z(6),PSIP(6),PSIP_X(6),PSIP_Y(6),PSIP_Z(6),ALD,INT1R,&
	&EFFSM,EFFSP
        REAL A,AD,AI,AIR,AK1,ALONG,AM0,AMZ,BETA1,CB,SB,CNX,CNY,CON,K1,K2,X0,DTHETA,AK2,AK3,AK4,R2PREC
        INTEGER I,I1,I2,IDOF,IFACSL,IJ,IJK,IK,ILIN,ILLOC_STAT,ILLOC_STAT2,ILLOC_STAT3&
        &,ILLOC_STAT4,ILLOC_STAT5,ILLOC_STAT6,ILLOC_STAT7,ILLOC_STAT8,ILLOC_STAT9&
        &,ILLOCOK,IMIN,IOUI,IR,IREC,ISYM,ITEST,J,JFACSL,JQ,JZ,K,KKK,KNC,&
        &N,N1,N2,N3,N4,NCONT,NFACSL,NIN,NJ,NL,NLIGNE,NM,NN2,NOMBPO&
        &,NPRINTW1,NPRINTW2,NR1,NR10,NR3,NR5,NR8,NR9,NTOT,NUMPT,NPASR,IPASR,NPASR2,NAN
        REAL RCEREXT,T,TPE1,TPE2,TPE3,TPE4,VA,W1,W2,W3,W4,WR,WR1,TEST,XL,LONG,LONGPRE,LONGCONT
	REAL R1,R2,DR,RC1,RC2,DRC,TBAR,G1,X1,X2,Y1,Y2,D1
        INTEGER IL,NICI,NHASKIND,LQTFP,NRCER,INDFACLIM,INDCONT,NTHETA,DOF,ICER,INDFAC2,NW,VDOF,INDFAC0,DOFSYM,IJPRINT
        REAL,DIMENSION(:),ALLOCATABLE ::RAYONS,IRCER,RCER
        COMPLEX TEMP,TEMPPRE,INTLP_DZ,INTLP_DZZ,INTLM_DZ,INTLM_DZZ,VARCONTM,VARCONTP,VS1BM,VS1BP,VE1M,VE1P,VE2M,VE2P,VE3M,VE3P,VE4M,VE4P
        COMPLEX VS4BM,VS4BP,VS1M,VS1P,VS2M,VS2P,VS3M,VS3P,VS4M,VS4P,VS5M,VS5P,VS6M,VS6P,VS7M,VS7P
	INTEGER COLLAPSE	! VARIABLE FICTIVE POUR PLIER / DEPLIER LE CODE
	
	NAN=0.
	NAN=NAN/NAN
write(*,*) 'checkkk'
!        !!!!!!!!!!!!!                                           !!!!!!!!!!!!!!!!!
DO 001 COLLAPSE=0,0!!!!!!           OUVERTURE ET ENREGISTREMENT DE LA GEOMETRIE     !!!!!!!!!
!     !!!!!!!!!!!!!                                           !!!!!!!!!!!!!!!!!


      OPEN(7,FILE="ID.dat")
      READ(7,*) lID
      READ(7,*) ID
      CLOSE(7)
001 ENDDO


    !!!!!!!!!!!!!                                           !!!!!!!!!!!!!!!!!
DO 002 COLLAPSE=0,0!!!!!     OUVERTURE ET ENREGISTREMENT DE GEOMETRIE COMPLETE        !!!!!!
    !!!!!!!!!!!!!                                           !!!!!!!!!!!!!!!!!
        NOMF4=ID(1:lID)//'/QTF/FA.RES'
        INQUIRE(FILE=NOMF4,EXIST=FICHEY)
!	PRINT *, FICHEY,4*4*NFA
        OPEN(UNIT=12,FILE=NOMF4,ACCESS='DIRECT',STATUS='UNKNOWN',RECL=4*4*NFA)
        READ(12,REC=1)NC,NCO,NSYM,NP,NFAC,IXX,XEFF,YEFF,ZEFF,&
        & (IMXC(I),I=1,NCO),(IPOS(I),I=1,NC),BP,T,IMIN,H,AMZ,ILIN,&
        & RHO,VA,BETA,WR,AM0,NIN,(AIND(I),I=1,NIN)
	WRITE(*,*)'NC ',NC,'NCO ',NCO,'NSYM ',NSYM,'NP ',NP,'NFAC ',NFAC,'IXX ',IXX,'M_EFF ',XEFF,YEFF,ZEFF,&
        & 'IMXC ',(IMXC(I),I=1,NCO),'IPOS ',(IPOS(I),I=1,NC),'BP ',BP,'T ',T,'IMIN ',IMIN,'H ',H,'AMZ ',AMZ,'ILIN ',ILIN,&
        & 'RHO ',RHO,'VA ',VA,'BETA ',BETA,'WR ',WR,'AM0 ',AM0,'NIN ',NIN,'AIND ',(AIND(I),I=1,NIN)
        READ(12,REC=2)(X(I),I=1,NP)
        READ(12,REC=3)(Y(I),I=1,NP)
        READ(12,REC=4)(Z(I),I=1,NP)
        READ(12,REC=5)(M1(I),I=1,NFAC),(M2(I),I=1,NFAC),&
        &(M3(I),I=1,NFAC),(M4(I),I=1,NFAC)

	IMX = NFAC

        READ(12,REC=6)(P(I),I=1,NFAC),(Q(I),I=1,NFAC),(R(I),I=1,NFAC)
        READ(12,REC=7)(XM(I),I=1,NFAC),(YM(I),I=1,NFAC),(ZM(I),I=1,NFAC)
        READ(12,REC=8)(AIRE(I),I=1,NFAC),(TDIS(I),I=1,NFAC),&
        &(DIST(I),I=1,NFAC)
        I1=NFAC+1
        READ(12,REC=9)(XM(I),I=I1,IXX),(YM(I),I=I1,IXX),(ZM(I),I=I1,IXX),&
        &(IND(I),I=1,IXX-NFAC)
        JQ=6*NC
        READ(12,REC=10)(((AIN(I,J,K),I=1,6),J=1,6),&
        &((ASH(I,J,K),I=1,6),J=1,6),K=1,NC),((RAID(I,J),I=1,JQ),J=1,JQ),&
        &((AMOR(I,J),I=1,JQ),J=1,JQ)
        CLOSE(12)

        NFFL=IXX-NFAC!NOMBRE DE LIGNE DE LA SURFACE DE FLOTAISON
        WRITE(*,*)'NFAC=',NFAC,'NFFL=',NFFL,'IXX=',IXX
        NL=NFAC+NFFL!NL=IXX
        XCDG=XEFF
        YCDG=YEFF
        ZCDG=ZEFF
        NDEB=0
        NFIN=NFAC+NFFL

        DO I=1,NFFL
            LK(1)=M1(IND(I))
            LK(2)=M2(IND(I))
            LK(3)=M3(IND(I))
            LK(4)=M4(IND(I))
            LK(5)=LK(1)
            P(NFAC+I)=P(IND(I))
            Q(NFAC+I)=Q(IND(I))
            R(NFAC+I)=0.
        ! LES QUANTITES N'ONT PAS ETE CALCULEES EN Z=0 A LA FLOTTAISON
        ! CEPENDANT ECRIRE ZSL=0 PERMET D'ETRE EXACT DANS LA GEOMETRIE (LES CN)
            ZM(IMX+I)=0.
            DO J=1,4
                TEST=(X(LK(J))-X(LK(J+1)))**2+(Y(LK(J))-Y(LK(J+1)))**2
                IF(ABS(Z(LK(J)))+ABS(Z(LK(J+1))) < 1.E-05 .AND. TEST > 1.E-5)THEN
                    AIRE(NFAC+I)=SQRT(TEST)
                ! !   AIRE(I),I>NFAC, EST LA LONGUEUR DES COTES A LA FLOTTAISON
                ENDIF
            ENDDO
       ENDDO
    !
        DO I=1,NL
            CN(I,1)=P(I)
            CN(I,2)=Q(I)
            CN(I,3)=R(I)
            CN(I,4)=(YM(I)-YEFF)*CN(I,3)-(ZM(I)-ZEFF)*CN(I,2)
            CN(I,5)=(ZM(I)-ZEFF)*CN(I,1)-(XM(I)-XEFF)*CN(I,3)
            CN(I,6)=(XM(I)-XEFF)*CN(I,2)-(YM(I)-YEFF)*CN(I,1)
        END DO
    !
        BETA=BETA/RADD
        CB=COS(BETA)
        SB=SIN(BETA)
        NJ=NSYM+1
	DOFSYM=1
	IF(NJ==2 .AND. BETA==0) DOFSYM=2
    !
    ! ---- FICHIERS DES QUANTITES DU PREMIER ORDRE  -----
        NOMB1=ID(1:lID)//'/QTF/B1.RES'
        NOMB2=ID(1:lID)//'/QTF/B2.RES'
        NOMB3=ID(1:lID)//'/QTF/B3.RES'
        NOMB4=ID(1:lID)//'/QTF/B4.RES'
    ! ---- FICHIERS PROBLEMES ADDITIONNELS DE RADIATION  -----
        NOMH1=ID(1:lID)//'/QTF/H1.RES'
        NOMH2=ID(1:lID)//'/QTF/H2.RES'
        NOMH3=ID(1:lID)//'/QTF/H3.RES'
        NOMH4=ID(1:lID)//'/QTF/H4.RES'
        NR1=3+24*NC+72*NC**2+NFFL*2*NJ
        NR3=NL*2*NJ

        OPEN(21,FILE=NOMB1,STATUS='UNKNOWN',ACCESS='DIRECT',RECL=4*NR1)
        OPEN(22,FILE=NOMB2,STATUS='UNKNOWN',ACCESS='DIRECT',RECL=4*NR3)
        OPEN(23,FILE=NOMB3,STATUS='UNKNOWN',ACCESS='DIRECT',RECL=4*NR3)
        OPEN(24,FILE=NOMB4,STATUS='UNKNOWN',ACCESS='DIRECT',RECL=4*NR3)
    !
        NOMB5=ID(1:lID)//'/QTF/AH.RES'
        OPEN(UNIT=40,FILE=NOMB5,STATUS='UNKNOWN')
    !
    !
!~         PRINT*,'LONGUEUR D''ADIMENSIONNALISATION ?'
    !        READ*,XL
        XL=1
        AD=RHO*G*XL
    ! SOMMATION SUR 1 SEUL CORPS
        KNC=1
    !
    ! PROCEDURE VALABLE SI W(NT(I)-NT(I-1))=W(I)-W(I-1)
        READ(LL,*) N
!~ 	WRITE(*,*) 'NOMNRE DE PULSATION POUR LA BASE HYDRO',N
!~      WRITE(LE,*)' ENTRER LES NUMEROS D''ENREGISTREMENTS DANS L''ORDRE'
!~      WRITE(LE,*)' DES PULSATIONS CROISSANTES (PERIODES DECROISSANTES)'
	READ(LL,*) (NT(I),I=1,N)
        READ(LL,*) LQTFP
        READ(LL,*) 
        READ(LL,*) 
        READ(LL,*) 
        READ(LL,*) Louthasfs,NPRINTW1,NPRINTW2,IJPRINT
	READ(LL,*) NRCER
	ALLOCATE(RCER(NRCER))
	ALLOCATE(IRCER(NRCER))
	READ(LL,*) (IRCER(I),I=1,NRCER)
	
!!!!!!!!!!!!!! version matrice carre pour les QTF+!!!!!!!!!!!!!!!!!!!!!!
!~        IF (LHASK>1 .AND. LQTFP==1) THEN                               
! SI LES QTF+ SONT CALCULES, IL FAUT REDUIRE LE NOMBRE DE PULSATION
!~              NHASKIND=N/2
!~        ELSE
!~              NHASKIND=N
!~        ENDIF
!~        PRINT*, 'N =',N,'NHASKIND =',NHASKIND
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!~         PRINT*,'CALCUL AUTOMATIQUE:1, CAS TEST:#1'
    !        READ(*,*)ITEST
        ITEST=1
        IF(ITEST == 1)THEN
        ! CALCUL AUTOMATIQUE
            NN2=0
        ELSE
        ! CAS TEST
            PRINT*,'NOMBRE DE PERIODES COMBINEES ?'
            READ(*,*)NM
!~             NN2=NHASKIND-NM
            NN2=N-NM
        ENDIF
002 ENDDO


    !!!!!!!!!!!!!                                                        !!!!!!!!!!!!!!!!!
! DO 003 COLLAPSE=0,0!!!!!               IMPORTATION DES FONCTIONS DE GREEN             !!!!!!
!     !!!!!!!!!!!!!                                           !!!!!!!!!!!!!!!!!
! 	NOMGRUN = ID(1:lID)//'/QTF/GRUN.QAT'
!         OPEN(UNIT=44,FILE=NOMGRUN,FORM='UNFORMATTED',STATUS='OLD')
!         READ(44)IR,JZ,(XR(I),I=1,IR),(XZ(J),J=1,JZ)
!         DO J=1,JZ
!             READ(44)(APD1X(I,J),I=1,IR),(APD1Z(I,J),I=1,IR),&
!             &(APD2X(I,J),I=1,IR),(APD2Z(I,J),I=1,IR)
!         END DO
!         CLOSE(UNIT=44)
!         APDXC=CMPLX(APD1X,APD2X)
!         APDZC=CMPLX(APD1Z,APD2Z)
! 003     ENDDO


    !!!!!!!!!!!!!                                                                             !!!!!!!!!!!!!!!!!
DO 004 COLLAPSE=0,0!!!!!   IMPORTATION DES MAILLAGES - POTENTIELS / ALLOCATIONS DES VARIABLES              !!!!!!
    !!!!!!!!!!!!!                                           !!!!!!!!!!!!!!!!!

        NR9=2*2*4*NFASL*2
        OPEN(11,FILE='SF_L12.RES',STATUS='OLD',ACCESS='DIRECT',RECL=NR9)
        READ(11,REC=1)NSYMY,NFACSL,NCONT,NOMBPO,NLIGNE,RCEREXT,NPASR
        WRITE(*,*) 'NSYMY ',NSYMY,'NFACSL ',NFACSL,'NCONT ',NCONT,'NOMBPO ',NOMBPO,'NLIGNE ',NLIGNE,'RCEREXT ',RCEREXT,'NPASR ',NPASR
        READ(11,REC=2)(XSL(I),YSL(I),I=1,NOMBPO)
        READ(11,REC=3)(XMSLF(I),YMSLF(I),I=1,NFACSL),(XMSLC(I),YMSLC(I),I=1,NCONT),(XMSLL(I),YMSLL(I),I=1,NLIGNE)
        READ(11,REC=4)(AIRESLF(I),I=1,NFACSL),(AIRESLC(I),I=1,NCONT)
        READ(11,REC=5)(CNSLC(1,I),CNSLC(2,I),I=1,NCONT)
        READ(11,REC=6)(M1SLF(I),M2SLF(I),I=1,NFACSL),(M1SLC(I),M2SLC(I),I=1,NCONT)
        READ(11,REC=7)(M3SLF(I),M4SLF(I),I=1,NFACSL)
        CLOSE(11)
        OPEN(10,FILE=ID(1:lID)//'/mesh/SF_L12_2.dat')
        WRITE(10,*)'   2   ',NSYM
        DO NUMPT=1,NOMBPO
            WRITE(10,*) NUMPT,XSL(NUMPT),YSL(NUMPT),0.
        END DO
        WRITE(10,*)'0. 0. 0. 0.'
        DO KKK=1,NFACSL
            WRITE(10,*)M1SLF(KKK),M2SLF(KKK),M3SLF(KKK),M4SLF(KKK)
        END DO
        WRITE(10,*)'0. 0. 0. 0.'
        CLOSE(10)

        NTOT=NFACSL+NCONT+NLIGNE
!!!!!!!!!!!!!! version matrice carre pour les QTF+!!!!!!!!!!!!!!!!!!!!!!
!~         ALLOCATE(EFFM(6,NHASKIND,NHASKIND,NRCER),STAT=ILLOC_STAT9)
!~ 	IF (LQTFP .EQ. 1) ALLOCATE(EFFP(6,NHASKIND,NHASKIND,NRCER),STAT=ILLOC_STAT9)
!~         ALLOCATE(RAYONS(NPASR),STAT=ILLOC_STAT9)
!~         ALLOCATE(EFFVERIF(6,NHASKIND,NHASKIND,NPASR),STAT=ILLOC_STAT9)
!~         ALLOCATE(EFFVERIF2(6,NHASKIND,NHASKIND,NPASR),STAT=ILLOC_STAT9)
!~         ALLOCATE(EFFVERIFR2(6,NHASKIND,NHASKIND,NPASR),STAT=ILLOC_STAT9)
!~         ALLOCATE(EFFVERIFB(6,NHASKIND,NHASKIND,NPASR),STAT=ILLOC_STAT9)
!~         ALLOCATE(EFFVERIF4(6,NHASKIND,NHASKIND,NPASR),STAT=ILLOC_STAT9)
!~         ALLOCATE(S1C(6,NPASR),STAT=ILLOC_STAT9)
!~         ALLOCATE(S1CB(6,NPASR),STAT=ILLOC_STAT9)
!~         ALLOCATE(S2C(6,NPASR),STAT=ILLOC_STAT9)
!~         ALLOCATE(S3C(6,NPASR),STAT=ILLOC_STAT9)
!~         ALLOCATE(S4C(6,NPASR),STAT=ILLOC_STAT9)
!~         ALLOCATE(VINCSLF(2,3,NHASKIND,NFACSL),STAT = ILLOC_STAT6)!! SUR LES FACETTES
!~         ALLOCATE(VPERSLF(2,3,NHASKIND,NFACSL),STAT = ILLOC_STAT6)
!~         ALLOCATE(VTOTSLF(2,3,NHASKIND,NFACSL),STAT = ILLOC_STAT8)
!~         ALLOCATE(POTINCSLF(2,NHASKIND,NFACSL),STAT = ILLOC_STAT5)
!~         ALLOCATE(POTTOTSLF(2,NHASKIND,NFACSL),STAT = ILLOC_STAT7)
!~         ALLOCATE(POTPERSLF(2,NHASKIND,NFACSL),STAT = ILLOC_STAT7)
!~         ALLOCATE(POTRADSLF(2,6,N,NFACSL),STAT = ILLOC_STAT3)
!~         ALLOCATE(VRADSLF(2,3,6,N,NFACSL),STAT = ILLOC_STAT4)
!~ 	
!~         ALLOCATE(VINCSLC(2,3,NHASKIND,NCONT),STAT = ILLOC_STAT6)!! SUR LES CONTOURS
!~         ALLOCATE(VPERSLC(2,3,NHASKIND,NCONT),STAT = ILLOC_STAT6)
!~         ALLOCATE(VTOTSLC(2,3,NHASKIND,NCONT),STAT = ILLOC_STAT8)
!~         ALLOCATE(POTINCSLC(2,NHASKIND,NCONT),STAT = ILLOC_STAT5)
!~         ALLOCATE(POTTOTSLC(2,NHASKIND,NCONT),STAT = ILLOC_STAT7)
!~         ALLOCATE(POTPERSLC(2,NHASKIND,NCONT),STAT = ILLOC_STAT7)
!~         ALLOCATE(POTRADSLC(2,6,N,NCONT),STAT = ILLOC_STAT3)
!~         ALLOCATE(VRADSLC(2,3,6,N,NCONT),STAT = ILLOC_STAT4)
!~ 	
!~         ALLOCATE(VINCSLL(2,3,NHASKIND,NLIGNE),STAT = ILLOC_STAT6)!! SUR LA LIGNE
!~         ALLOCATE(VPERSLL(2,3,NHASKIND,NLIGNE),STAT = ILLOC_STAT6)
!~         ALLOCATE(VTOTSLL(2,3,NHASKIND,NLIGNE),STAT = ILLOC_STAT8)
!~         ALLOCATE(POTINCSLL(2,NHASKIND,NLIGNE),STAT = ILLOC_STAT5)
!~         ALLOCATE(POTTOTSLL(2,NHASKIND,NLIGNE),STAT = ILLOC_STAT7)
!~         ALLOCATE(POTPERSLL(2,NHASKIND,NLIGNE),STAT = ILLOC_STAT7)
!~         ALLOCATE(POTRADSLL(2,6,N,NLIGNE),STAT = ILLOC_STAT3)
!~         ALLOCATE(VRADSLL(2,3,6,N,NLIGNE),STAT = ILLOC_STAT4)
!~ 	
!~ 	ALLOCATE(S1BM(6,NHASKIND,NHASKIND))
!~ 	ALLOCATE(S1BP(6,NHASKIND,NHASKIND))
!~ 	ALLOCATE(S4BM(6,NHASKIND,NHASKIND))
!~ 	ALLOCATE(S4BP(6,NHASKIND,NHASKIND))
!~ 	ALLOCATE(E1BM(6,NHASKIND,NHASKIND))
!~ 	ALLOCATE(E1BP(6,NHASKIND,NHASKIND))
!~ 	ALLOCATE(S1M(6,NHASKIND,NHASKIND))
!~ 	ALLOCATE(S1P(6,NHASKIND,NHASKIND))
!~ 	ALLOCATE(S2M(6,NHASKIND,NHASKIND))
!~ 	ALLOCATE(S2P(6,NHASKIND,NHASKIND))
!~ 	ALLOCATE(S3M(6,NHASKIND,NHASKIND))
!~ 	ALLOCATE(S3P(6,NHASKIND,NHASKIND))
!~ 	ALLOCATE(S4M(6,NHASKIND,NHASKIND))
!~ 	ALLOCATE(S4P(6,NHASKIND,NHASKIND))
!~ 	ALLOCATE(S5M(6,NHASKIND,NHASKIND))
!~ 	ALLOCATE(S5P(6,NHASKIND,NHASKIND))
!~ 	ALLOCATE(S6M(6,NHASKIND,NHASKIND))
!~ 	ALLOCATE(S6P(6,NHASKIND,NHASKIND))
!~ 	ALLOCATE(S7M(6,NHASKIND,NHASKIND))
!~ 	ALLOCATE(S7P(6,NHASKIND,NHASKIND))
!~ 	ALLOCATE(E1M(6,NHASKIND,NHASKIND))
!~ 	ALLOCATE(E1P(6,NHASKIND,NHASKIND))
!~ 	ALLOCATE(E2M(6,NHASKIND,NHASKIND))
!~ 	ALLOCATE(E2P(6,NHASKIND,NHASKIND))
!~ 	ALLOCATE(E3M(6,NHASKIND,NHASKIND))
!~ 	ALLOCATE(E3P(6,NHASKIND,NHASKIND))
!~ 	ALLOCATE(E4M(6,NHASKIND,NHASKIND))
!~ 	ALLOCATE(E4P(6,NHASKIND,NHASKIND))
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

!!!! version matrice antitriangulaire sup pour les QTF+ (0 ailleurs) !!!!
        ALLOCATE(EFFM(6,N,N,NRCER),STAT=ILLOC_STAT9)
	IF (LQTFP .EQ. 1) ALLOCATE(EFFP(6,N,N,NRCER),STAT=ILLOC_STAT9)
        ALLOCATE(RAYONS(NPASR),STAT=ILLOC_STAT9)
        ALLOCATE(EFFVERIF(6,N,N,NPASR),STAT=ILLOC_STAT9)
        ALLOCATE(EFFVERIF2(6,N,N,NPASR),STAT=ILLOC_STAT9)
        ALLOCATE(EFFVERIFR2(6,N,N,NPASR),STAT=ILLOC_STAT9)
        ALLOCATE(EFFVERIFB(6,N,N,NPASR),STAT=ILLOC_STAT9)
        ALLOCATE(EFFVERIF4(6,N,N,NPASR),STAT=ILLOC_STAT9)
        ALLOCATE(S1C(6,NPASR),STAT=ILLOC_STAT9)
        ALLOCATE(S1CB(6,NPASR),STAT=ILLOC_STAT9)
        ALLOCATE(S2C(6,NPASR),STAT=ILLOC_STAT9)
        ALLOCATE(S3C(6,NPASR),STAT=ILLOC_STAT9)
        ALLOCATE(S4C(6,NPASR),STAT=ILLOC_STAT9)
        ALLOCATE(VINCSLF(2,3,N,NFACSL),STAT = ILLOC_STAT6)!! SUR LES FACETTES
        ALLOCATE(VPERSLF(2,3,N,NFACSL),STAT = ILLOC_STAT6)
        ALLOCATE(VTOTSLF(2,3,N,NFACSL),STAT = ILLOC_STAT8)
        ALLOCATE(POTINCSLF(2,N,NFACSL),STAT = ILLOC_STAT5)
        ALLOCATE(POTTOTSLF(2,N,NFACSL),STAT = ILLOC_STAT7)
        ALLOCATE(POTPERSLF(2,N,NFACSL),STAT = ILLOC_STAT7)
        ALLOCATE(POTRADSLF(2,6,N,NFACSL),STAT = ILLOC_STAT3)
        ALLOCATE(VRADSLF(2,3,6,N,NFACSL),STAT = ILLOC_STAT4)
	
        ALLOCATE(VINCSLC(2,3,N,NCONT),STAT = ILLOC_STAT6)!! SUR LES CONTOURS
        ALLOCATE(VPERSLC(2,3,N,NCONT),STAT = ILLOC_STAT6)
        ALLOCATE(VTOTSLC(2,3,N,NCONT),STAT = ILLOC_STAT8)
        ALLOCATE(POTINCSLC(2,N,NCONT),STAT = ILLOC_STAT5)
        ALLOCATE(POTTOTSLC(2,N,NCONT),STAT = ILLOC_STAT7)
        ALLOCATE(POTPERSLC(2,N,NCONT),STAT = ILLOC_STAT7)
        ALLOCATE(POTRADSLC(2,6,N,NCONT),STAT = ILLOC_STAT3)
        ALLOCATE(VRADSLC(2,3,6,N,NCONT),STAT = ILLOC_STAT4)
	
        ALLOCATE(VINCSLL(2,3,N,NLIGNE),STAT = ILLOC_STAT6)!! SUR LA LIGNE
        ALLOCATE(VPERSLL(2,3,N,NLIGNE),STAT = ILLOC_STAT6)
        ALLOCATE(VTOTSLL(2,3,N,NLIGNE),STAT = ILLOC_STAT8)
        ALLOCATE(POTINCSLL(2,N,NLIGNE),STAT = ILLOC_STAT5)
        ALLOCATE(POTTOTSLL(2,N,NLIGNE),STAT = ILLOC_STAT7)
        ALLOCATE(POTPERSLL(2,N,NLIGNE),STAT = ILLOC_STAT7)
        ALLOCATE(POTRADSLL(2,6,N,NLIGNE),STAT = ILLOC_STAT3)
        ALLOCATE(VRADSLL(2,3,6,N,NLIGNE),STAT = ILLOC_STAT4)
	
	ALLOCATE(S1BM(6,N,N))
	ALLOCATE(S1BP(6,N,N))
	ALLOCATE(S4BM(6,N,N))
	ALLOCATE(S4BP(6,N,N))
	ALLOCATE(E1BM(6,N,N))
	ALLOCATE(E1BP(6,N,N))
	ALLOCATE(S1M(6,N,N))
	ALLOCATE(S1P(6,N,N))
	ALLOCATE(S2M(6,N,N))
	ALLOCATE(S2P(6,N,N))
	ALLOCATE(S3M(6,N,N))
	ALLOCATE(S3P(6,N,N))
	ALLOCATE(S4M(6,N,N))
	ALLOCATE(S4P(6,N,N))
	ALLOCATE(S5M(6,N,N))
	ALLOCATE(S5P(6,N,N))
	ALLOCATE(S6M(6,N,N))
	ALLOCATE(S6P(6,N,N))
	ALLOCATE(S7M(6,N,N))
	ALLOCATE(S7P(6,N,N))
	ALLOCATE(E1M(6,N,N))
	ALLOCATE(E1P(6,N,N))
	ALLOCATE(E2M(6,N,N))
	ALLOCATE(E2P(6,N,N))
	ALLOCATE(E3M(6,N,N))
	ALLOCATE(E3P(6,N,N))
	ALLOCATE(E4M(6,N,N))
	ALLOCATE(E4P(6,N,N))
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

        ILLOCOK=ILLOC_STAT+ILLOC_STAT2+ILLOC_STAT3+ILLOC_STAT4+ILLOC_STAT5+ILLOC_STAT6+ILLOC_STAT7+ILLOC_STAT8+ILLOC_STAT9
        IF (ILLOCOK/=0)THEN
            PRINT *,'ERROR'
            PRINT *,ILLOC_STAT,ILLOC_STAT2,ILLOC_STAT3,ILLOC_STAT4,ILLOC_STAT5,ILLOC_STAT6,ILLOC_STAT7,ILLOC_STAT8,ILLOC_STAT9
        ENDIF
        NTOT=NFACSL+NCONT+NLIGNE
        NR10=NTOT*2*2*4
        OPEN(12,FILE='POTENTIELS_SL.RES',ACCESS='DIRECT',RECL=2*NR10)
        DO IJK=1,N
            IREC=(IJK-1)*36
!~ 	    IF (IJK .LE. NHASKIND) THEN					! version matrice carre pour les QTF+
	    IF (IJK .LE. N) THEN					! version matrice antitriangulaire sup pour les QTF+ (0 ailleurs)
		READ(12,REC=IREC+1)(POTTOTSLF(1,IJK,IFACSL),IFACSL=1,NFACSL),(POTTOTSLC(1,IJK,IFACSL),IFACSL=1,NCONT),(POTTOTSLL(1,IJK,IFACSL),IFACSL=1,NLIGNE),(POTTOTSLF(2,IJK,IFACSL),IFACSL=1,NFACSL),(POTTOTSLC(2,IJK,IFACSL),IFACSL=1,NCONT),(POTTOTSLL(2,IJK,IFACSL),IFACSL=1,NLIGNE)
		READ(12,REC=IREC+2)(POTINCSLF(1,IJK,IFACSL),IFACSL=1,NFACSL),(POTINCSLC(1,IJK,IFACSL),IFACSL=1,NCONT),(POTINCSLL(1,IJK,IFACSL),IFACSL=1,NLIGNE),(POTINCSLF(2,IJK,IFACSL),IFACSL=1,NFACSL),(POTINCSLC(2,IJK,IFACSL),IFACSL=1,NCONT),(POTINCSLL(2,IJK,IFACSL),IFACSL=1,NLIGNE)
		READ(12,REC=IREC+3)(POTPERSLF(1,IJK,IFACSL),IFACSL=1,NFACSL),(POTPERSLC(1,IJK,IFACSL),IFACSL=1,NCONT),(POTPERSLL(1,IJK,IFACSL),IFACSL=1,NLIGNE),(POTPERSLF(2,IJK,IFACSL),IFACSL=1,NFACSL),(POTPERSLC(2,IJK,IFACSL),IFACSL=1,NCONT),(POTPERSLL(2,IJK,IFACSL),IFACSL=1,NLIGNE)
	    ENDIF
	    DO IK=1,6,DOFSYM
		READ(12,REC=IREC+3+IK)(POTRADSLF(1,IK,IJK,IFACSL),IFACSL=1,NFACSL),(POTRADSLC(1,IK,IJK,IFACSL),IFACSL=1,NCONT),(POTRADSLL(1,IK,IJK,IFACSL),IFACSL=1,NLIGNE),(POTRADSLF(2,IK,IJK,IFACSL),IFACSL=1,NFACSL),(POTRADSLC(2,IK,IJK,IFACSL),IFACSL=1,NCONT),(POTRADSLL(2,IK,IJK,IFACSL),IFACSL=1,NLIGNE)
	    ENDDO
            DO IDOF=1,3
!~ 		IF (IJK .LE. NHASKIND) THEN				! version matrice carre pour les QTF+
		IF (IJK .LE. N) THEN					! version matrice antitriangulaire sup pour les QTF+ (0 ailleurs)
		    READ(12,REC=IREC+10+9*(IDOF-1)) (VTOTSLF(1,IDOF,IJK,IFACSL),IFACSL=1,NFACSL),(VTOTSLC(1,IDOF,IJK,IFACSL),IFACSL=1,NCONT),(VTOTSLL(1,IDOF,IJK,IFACSL),IFACSL=1,NLIGNE),(VTOTSLF(2,IDOF,IJK,IFACSL),IFACSL=1,NFACSL),(VTOTSLC(2,IDOF,IJK,IFACSL),IFACSL=1,NCONT),(VTOTSLL(2,IDOF,IJK,IFACSL),IFACSL=1,NLIGNE)
		    READ(12,REC=IREC+11+9*(IDOF-1)) (VINCSLF(1,IDOF,IJK,IFACSL),IFACSL=1,NFACSL),(VINCSLC(1,IDOF,IJK,IFACSL),IFACSL=1,NCONT),(VINCSLL(1,IDOF,IJK,IFACSL),IFACSL=1,NLIGNE),(VINCSLF(2,IDOF,IJK,IFACSL),IFACSL=1,NFACSL),(VINCSLC(2,IDOF,IJK,IFACSL),IFACSL=1,NCONT),(VINCSLL(2,IDOF,IJK,IFACSL),IFACSL=1,NLIGNE)
		    READ(12,REC=IREC+12+9*(IDOF-1)) (VPERSLF(1,IDOF,IJK,IFACSL),IFACSL=1,NFACSL),(VPERSLC(1,IDOF,IJK,IFACSL),IFACSL=1,NCONT),(VPERSLL(1,IDOF,IJK,IFACSL),IFACSL=1,NLIGNE),(VPERSLF(2,IDOF,IJK,IFACSL),IFACSL=1,NFACSL),(VPERSLC(2,IDOF,IJK,IFACSL),IFACSL=1,NCONT),(VPERSLL(2,IDOF,IJK,IFACSL),IFACSL=1,NLIGNE)
		ENDIF
                DO IK=1,6,DOFSYM
		    READ(12,REC=IREC+12+(IDOF-1)*9+IK) (VRADSLF(1,IDOF,IK,IJK,IFACSL),IFACSL=1,NFACSL),(VRADSLC(1,IDOF,IK,IJK,IFACSL),IFACSL=1,NCONT),(VRADSLL(1,IDOF,IK,IJK,IFACSL),IFACSL=1,NLIGNE),(VRADSLF(2,IDOF,IK,IJK,IFACSL),IFACSL=1,NFACSL),(VRADSLC(2,IDOF,IK,IJK,IFACSL),IFACSL=1,NCONT),(VRADSLL(2,IDOF,IK,IJK,IFACSL),IFACSL=1,NLIGNE)
		ENDDO
	    ENDDO
	ENDDO
        CLOSE(12)
    
004 ENDDO!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!





!!!!PLOT DISTANCE RADIALE!!!!


!~     PRINT *,'RCEREXT=',RCEREXT

    A=0
    LONGPRE=0
    NICI=0
    NTHETA=NFACSL/NPASR
   
   
!~     NPRINTW1=20 !NHASKIND
!~     NPRINTW2=19 !NHASKIND-1
!~     IJPRINT=3
    PRINT*, 'NPRINTW1 =',NPRINTW1,'NPRINTW2 =',NPRINTW2,'DOF_PRINT =',IJPRINT
    
    WRITE(FMT1,'(I2.2)') NPRINTW1
    WRITE(FMT2,'(I2.2)') NPRINTW2
    WRITE(FMTV,'(I1)') IJPRINT
    
    IF ( Louthasfs==1 ) THEN
	
	OPEN(178,FILE=ID(1:lID)//'/results/QTF/Appendix/PLOT_DZZ_CONT_W'//TRIM(FMT1)//'_W'//TRIM(FMT2)//'_DOF'//TRIM(FMTV)//'.dat')
	OPEN(128,FILE=ID(1:lID)//'/results/QTF/Appendix/PLOTSURF_W'//TRIM(FMT1)//'_W'//TRIM(FMT2)//'_DOF'//TRIM(FMTV)//'.dat')
	OPEN(122,FILE=ID(1:lID)//'/results/QTF/Appendix/PLOT_DZ_INT_W'//TRIM(FMT1)//'_W'//TRIM(FMT2)//'_DOF'//TRIM(FMTV)//'.dat')
	OPEN(121,FILE=ID(1:lID)//'/results/QTF/Appendix/PLOT_DZZ_INT_W'//TRIM(FMT1)//'_W'//TRIM(FMT2)//'_DOF'//TRIM(FMTV)//'.dat')
	OPEN(130,FILE=ID(1:lID)//'/results/QTF/Appendix/PLOTLIGNE_W'//TRIM(FMT1)//'_W'//TRIM(FMT2)//'_DOF'//TRIM(FMTV)//'.dat')
	OPEN(137,FILE=ID(1:lID)//'/results/QTF/Appendix/DZ_W'//TRIM(FMT1)//'_W'//TRIM(FMT2)//'_DOF'//TRIM(FMTV)//'.dat')
	OPEN(138,FILE=ID(1:lID)//'/results/QTF/Appendix/DZZ_2D_W'//TRIM(FMT1)//'_W'//TRIM(FMT2)//'_DOF'//TRIM(FMTV)//'.dat')
	OPEN(134,FILE=ID(1:lID)//'/results/QTF/Appendix/DZZ_CONT_W'//TRIM(FMT1)//'_W'//TRIM(FMT2)//'_DOF'//TRIM(FMTV)//'.dat')
	OPEN(132,FILE=ID(1:lID)//'/results/QTF/Appendix/comp_W'//TRIM(FMT1)//'_W'//TRIM(FMT2)//'_DOF'//TRIM(FMTV)//'.dat')
	
	
	WRITE(178,*) 'X     ','Y     ','CX     ','CY     '&
	&,'INTEGRANDE SUR LE CONTOUR DIFF PARTIE REELLE     ','INT CONT DIFF IM     ','[INT CONT SOM RE     ','INT CONT SOM IM]'
	WRITE(128,*) 'X     ','Y     ','PHI1 PARTIE REELLE     ','IM(PHI1)     ','PHI1_X  .._Y  .._Z     ','PHII1 ...','PHIP1 ...','....2','PSIM  .._X  ....','[PSIP .._X ...]'
	WRITE(122,*) 'X     ','Y     ','INTEGRANDE DZ (S1-3) DIFF SUR LA SL PARTIE RELLE     ','INT DIFF IM     ','[INT SOM RE     ','INT SOM IM]     '
	WRITE(121,*) 'X     ','Y     ','INTEGRANDE DZZ (S4-7) DIFF SUR LA SL PARTIE RELLE     ','INT DIFF IM     ','[INT SOM RE     ','INT SOM IM]     '
	WRITE(130,*) 'X     ','Y     ','PHI1 PARTIE REELLE     ','IM(PHI1)     ','PHI1_X  .._Y  .._Z     ','PHII1 ...','PHIP1 ...','....2','PSIM  .._X  ....','[PSIP .._X ...]'
	WRITE(137,*) 'Rext    ','REAL PART DZ INTM    ','IM DZ INTM','[RE DZ INTP    ','IM DZ INTP]'
	WRITE(138,*) 'Rext    ','REAL PART DZZ INTM2D    ','IM DZZ INTM2D','[RE DZZ INTP2D    ','IM DZZ INTP2D]'
	WRITE(134,*) 'Rext    ','REAL PART DZZ INTMCONT    ','IM DZZ INTMCONT','[RE DZZ INTPCONT    ','IM DZZ INTPCONT]'
	WRITE(132,*) 'Rext    ','REAL PART S1-7+E1-4 INTM    ','IM S1-7+E1-4 INTM','[RE S1-7+E1-4 INTP    ','IM S1-7+E1-4 INTP]'
    ENDIF
    
    S1BM=CMPLX(0.,0.)
    S4BM=CMPLX(0.,0.)
    
    IF (LQTFP==1) THEN
      S1BP=CMPLX(0.,0.)
      S4BP=CMPLX(0.,0.)
    ENDIF
    
    IF (Louthasfs==1) THEN
    
      S1M=CMPLX(0.,0.)
      S2M=CMPLX(0.,0.)
      S3M=CMPLX(0.,0.)
      S4M=CMPLX(0.,0.)
      S5M=CMPLX(0.,0.)
      S6M=CMPLX(0.,0.)
      S7M=CMPLX(0.,0.)

      IF (LQTFP==1) THEN
      
	S1P=CMPLX(0.,0.)
	S2P=CMPLX(0.,0.)
	S3P=CMPLX(0.,0.)
	S4P=CMPLX(0.,0.)
	S5P=CMPLX(0.,0.)
	S6P=CMPLX(0.,0.)
	S7P=CMPLX(0.,0.)
	
      ENDIF
    ENDIF
      
    AI=0.
    INDFACLIM=0
    ! BOUCLE SUR LES RAYONS LIMITES
    DO 215 ICER=1,NRCER
	! VALABLE UNIQUEMENT POUR UN MAILLAGE SUTRUCTURE DE LA SURFACE LIBRE
	! FACES
	INDFAC0=INDFACLIM
	INDFACLIM=NTHETA*IRCER(ICER)
	R1=SQRT(XMSLF(INDFACLIM)**2+YMSLF(INDFACLIM)**2)
	R2=SQRT(XMSLF(INDFACLIM+1)**2+YMSLF(INDFACLIM+1)**2)
	INDFAC2=(NTHETA)*(IRCER(ICER)-1)
	DR=ABS(R1-SQRT(XMSLF(INDFAC2)**2+YMSLF(INDFAC2)**2))
	
	! CONTOURS
	INDCONT=NCONT/2
	RC1=SQRT(XMSLF(INDCONT)**2+YMSLF(INDCONT)**2)
	RC2=SQRT(XMSLF(INDCONT+1)**2+YMSLF(INDCONT+1)**2)
	DRC=ABS(RC1-SQRT(XMSLF(INDCONT+NTHETA)**2+YMSLF(INDCONT+NTHETA)**2))
	
	RCER(ICER)=(R1+R2)/2/COS(PI/NJ/NTHETA)
	
	IF (R2-R1>DR/2 .AND. RC2-RC1>DRC/4. .AND. INDCONT==NTHETA) THEN 
	! ON EST ALORS A LA FIN DE L'ARC DE CERCLE DE RAYON ~RCER
	
	! INTERPOLATION DES POTENTIELS POUR NE PAS AVOIR A RELANCER LE PREPROC

	DO IFACSL=1,INDCONT
	    X1=XSL(M1SLF(IFACSL+INDFACLIM))
	    Y1=YSL(M1SLF(IFACSL+INDFACLIM))
	    X2=XSL(M2SLF(IFACSL+INDFACLIM))
	    Y2=YSL(M2SLF(IFACSL+INDFACLIM))
	    XMSLC(IFACSL+INDCONT)=0.5*(X1+X2)
	    YMSLC(IFACSL+INDCONT)=0.5*(Y1+Y2)
	    G1=SQRT((X2-X1)**2+(Y2-Y1)**2)
	    D1=SQRT((X1+X2)**2+(Y1+Y2)**2)/2
	    AIRESLC(IFACSL+INDCONT)=G1
	    CNSLC(1,IFACSL+INDCONT)=(Y2-Y1)/G1
	    CNSLC(2,IFACSL+INDCONT)=-(X2-X1)/G1
	    TBAR=(D1-SQRT(XMSLF(IFACSL+INDFACLIM)**2+YMSLF(IFACSL+INDFACLIM)**2))/(SQRT(XMSLF(IFACSL+INDFACLIM-NTHETA)**2+YMSLF(IFACSL+INDFACLIM-NTHETA)**2)-SQRT(XMSLF(IFACSL+INDFACLIM)**2+YMSLF(IFACSL+INDFACLIM)**2))
	    DO ISYM=1,NJ
!~ 		DO NW=1,NHASKIND					! version matrice carre pour les QTF+
		DO NW=1,N						! version matrice antitriangulaire sup pour les QTF+ (0 ailleurs)
		    POTTOTSLC(ISYM,NW,IFACSL+INDCONT)=POTTOTSLF(ISYM,NW,IFACSL+INDFACLIM-NTHETA)*TBAR+POTTOTSLF(ISYM,NW,IFACSL+INDFACLIM)*(1-TBAR)
		    POTPERSLC(ISYM,NW,IFACSL+INDCONT)=POTPERSLF(ISYM,NW,IFACSL+INDFACLIM-NTHETA)*TBAR+POTPERSLF(ISYM,NW,IFACSL+INDFACLIM)*(1-TBAR)
		    POTINCSLC(ISYM,NW,IFACSL+INDCONT)=POTINCSLF(ISYM,NW,IFACSL+INDFACLIM-NTHETA)*TBAR+POTINCSLF(ISYM,NW,IFACSL+INDFACLIM)*(1-TBAR)
		    DO VDOF=1,3
		    	VTOTSLC(ISYM,VDOF,NW,IFACSL+INDCONT)=VTOTSLF(ISYM,VDOF,NW,IFACSL+INDFACLIM-NTHETA)*TBAR+VTOTSLF(ISYM,VDOF,NW,IFACSL+INDFACLIM)*(1-TBAR)
			VPERSLC(ISYM,VDOF,NW,IFACSL+INDCONT)=VPERSLF(ISYM,VDOF,NW,IFACSL+INDFACLIM-NTHETA)*TBAR+VPERSLF(ISYM,VDOF,NW,IFACSL+INDFACLIM)*(1-TBAR)
			VINCSLC(ISYM,VDOF,NW,IFACSL+INDCONT)=VINCSLF(ISYM,VDOF,NW,IFACSL+INDFACLIM-NTHETA)*TBAR+VINCSLF(ISYM,VDOF,NW,IFACSL+INDFACLIM)*(1-TBAR)
		    ENDDO
		ENDDO
		DO NW=1,N
		    DO DOF=1,6,DOFSYM
			POTRADSLC(ISYM,DOF,NW,IFACSL+INDCONT)=POTRADSLF(ISYM,DOF,NW,IFACSL+INDFACLIM-NTHETA)*TBAR+POTRADSLF(ISYM,DOF,NW,IFACSL+INDFACLIM)*(1-TBAR)
		        DO VDOF=1,3
			    VRADSLC(ISYM,VDOF,DOF,NW,IFACSL+INDCONT)=VRADSLF(ISYM,VDOF,DOF,NW,IFACSL+INDFACLIM-NTHETA)*TBAR+VRADSLF(ISYM,VDOF,DOF,NW,IFACSL+INDFACLIM)*(1-TBAR)
			ENDDO
		    ENDDO
		ENDDO
	    ENDDO
	ENDDO
    
    N1=0
    N2=0
    N3=0
    N4=0
!~     DO 200 I1=1,NHASKIND						! version matrice carre pour les QTF+
    DO 200 I1=1,N							! version matrice antitriangulaire sup pour les QTF+ (0 ailleurs)
        DO 200 I2=1,I1
            N1=NT(I1)
            N2=NT(I2)
            IF (I1==I2) THEN
	      N3=0
	    ELSE
	      N3=NT(I1-I2)
	    ENDIF
	    IF (I1+I2.LE.N .AND. LQTFP .EQ. 1) THEN
	      N4=NT(I1+I2) !NUMERO D'ENREGISTREMENT PULSATION SOMME
	    ELSE
	      N4=0
	    ENDIF
            
	    WRITE(LE,1977,ADVANCE="NO") N1,N2,N3,N4,RCER(ICER),CHAR(13)
	    
	    IF(N1 /= 0)THEN
                READ(21,REC=N1)TPE1,BETA,AK1
		W1=2.*PI/TPE1
                IF(H.LT.1.E10)THEN
                    K1=X0(AK1*H)/H
                ELSE
                    K1=AK1
                ENDIF
            ELSE
                PRINT *,'ERREUR D''ENREGISTREMENT 0'
            ENDIF
            IF(N2 /= 0)THEN
                READ(21,REC=N2)TPE2,BETA,AK2
		W2=2.*PI/TPE2
                IF(H.LT.1.E10)THEN
                    K2=X0(AK2*H)/H
                ELSE
                    K2=AK2
                ENDIF
            ELSE
                PRINT *,'ERREUR D''ENREGISTREMENT 0'
            ENDIF
            IF(N3 /= 0)THEN
                READ(21,REC=N3)TPE3,BETA,AK3
		W3=2.*PI/TPE3
            ELSE
                TPE3=NAN
                BETA=NAN
                AK3=NAN
                W3=0
            ENDIF
	    IF(N4 /= 0)THEN
                READ(21,REC=N4)TPE4,BETA,AK4
		W4=2.*PI/TPE4
            ELSE
                TPE4=NAN
                BETA=NAN
                AK4=NAN
                W4=NAN
            ENDIF

	    IF ( Louthasfs==1 .AND. N1==NPRINTW1 .AND. N2==NPRINTW2 .AND. ICER==1) THEN
	      IF (N4/=0) THEN
		WRITE(178,*) 'W1=',W1,'W2=',W2,'W-=',W3,'W+=',W4
		WRITE(128,*) 'W1=',W1,'W2=',W2,'W-=',W3,'W+=',W4
		WRITE(122,*) 'W1=',W1,'W2=',W2,'W-=',W3,'W+=',W4
		WRITE(130,*) 'W1=',W1,'W2=',W2,'W-=',W3,'W+=',W4
		WRITE(137,*) 'W1=',W1,'W2=',W2,'W-=',W3,'W+=',W4
		WRITE(138,*) 'W1=',W1,'W2=',W2,'W-=',W3,'W+=',W4
		WRITE(134,*) 'W1=',W1,'W2=',W2,'W-=',W3,'W+=',W4
		WRITE(132,*) 'W1=',W1,'W2=',W2,'W-=',W3,'W+=',W4
	      ELSE
		WRITE(178,*) 'W1=',W1,'W2=',W2,'W-=',W3
		WRITE(128,*) 'W1=',W1,'W2=',W2,'W-=',W3
		WRITE(122,*) 'W1=',W1,'W2=',W2,'W-=',W3
		WRITE(130,*) 'W1=',W1,'W2=',W2,'W-=',W3
		WRITE(137,*) 'W1=',W1,'W2=',W2,'W-=',W3
		WRITE(138,*) 'W1=',W1,'W2=',W2,'W-=',W3
		WRITE(134,*) 'W1=',W1,'W2=',W2,'W-=',W3
		WRITE(132,*) 'W1=',W1,'W2=',W2,'W-=',W3
	      ENDIF
	    ENDIF

	    DO 210 IFACSL=INDFAC0+1,INDFACLIM
	      DO 210 ISYM=1,NJ
                PHI1=POTTOTSLF(ISYM,N1,IFACSL)
                PHIP1=POTPERSLF(ISYM,N1,IFACSL)
                PHII1=POTINCSLF(ISYM,N1,IFACSL)

                PHI2=POTTOTSLF(ISYM,N2,IFACSL)
                PHIP2=POTPERSLF(ISYM,N2,IFACSL)
                PHII2=POTINCSLF(ISYM,N2,IFACSL)

                PHI1_X=VTOTSLF(ISYM,1,N1,IFACSL)
                PHIP1_X=VPERSLF(ISYM,1,N1,IFACSL)
                PHII1_X=VINCSLF(ISYM,1,N1,IFACSL)

                PHI1_Y=VTOTSLF(ISYM,2,N1,IFACSL)
                PHIP1_Y=VPERSLF(ISYM,2,N1,IFACSL)
                PHII1_Y=VINCSLF(ISYM,2,N1,IFACSL)

                PHI1_Z=VTOTSLF(ISYM,3,N1,IFACSL)
                PHIP1_Z=VPERSLF(ISYM,3,N1,IFACSL)
                PHII1_Z=VINCSLF(ISYM,3,N1,IFACSL)

                PHI2_X=VTOTSLF(ISYM,1,N2,IFACSL)
                PHIP2_X=VPERSLF(ISYM,1,N2,IFACSL)
                PHII2_X=VINCSLF(ISYM,1,N2,IFACSL)

                PHI2_Y=VTOTSLF(ISYM,2,N2,IFACSL)
                PHIP2_Y=VPERSLF(ISYM,2,N2,IFACSL)
                PHII2_Y=VINCSLF(ISYM,2,N2,IFACSL)

                PHI2_Z=VTOTSLF(ISYM,3,N2,IFACSL)
                PHIP2_Z=VPERSLF(ISYM,3,N2,IFACSL)
                PHII2_Z=VINCSLF(ISYM,3,N2,IFACSL)

                AIR=AIRESLF(IFACSL)
                LONG=SQRT(XMSLF(IFACSL)**2+YMSLF(IFACSL)**2)

        !!!!!!!!!!!                                                                        !!!!!!!!!!!
        !!!!   NOUS DEVONS CODER I(W1-W2)(GRAD PHI1 GRAD PHIP2* + GRAD PHIP1 GRAD PHII2) PSI^- DS  !!!!!
        !!!!!!!!!!!                                                                         !!!!!!!!!!
	! SiP/M		: INTEGRALE SUR LA CARENE (P: SOMME DE PULSATION / M: DIFF) --> SORITES COMPLEMENTAIRE
	! 			i=1,3 : PARTIE AUX DERIVEE PREMIERES
	!			i=4,7 : PARTIE AUX DERIVEE SECONDE
	! S1BP/M 	: FORMULATION CONFORME AU PAPIER
	!			S1BP/M = S1P/M + S2P/M + S3P/M
	! S4BP/M 	: FORMULATION CONFORME AU PAPIER
	!			S4BP/M = S4P/M + S5P/M + S6P/M + S7P/M
		IF (N3 /=0 ) THEN
		    VS1BM=	+ ZI*(W1-W2)*					&
		    &                 (PHI1_X*CONJG(PHI2_X)+		&
		    &                  PHI1_Y*CONJG(PHI2_Y)+		&
		    &                  PHI1_Z*CONJG(PHI2_Z)-		&
		    &                  PHII1_X*CONJG(PHII2_X)-		&
		    &                  PHII1_Y*CONJG(PHII2_Y)-		&
		    &                  PHII1_Z*CONJG(PHII2_Z) )		&
		    &       +1/(2.*G)*  					&
		    &               (-ZI*W1*PHI1*(-W2**2*CONJG(PHI2_Z))	&
		    &                +ZI*W2*CONJG(PHI2)*(-W1**2*PHI1_Z) )	&
		    &       -1/(2.*G)*  					&
		    &               (-ZI*W1*PHII1*(-W2**2*CONJG(PHII2_Z))	&
		    &                +ZI*W2*CONJG(PHII2)*(-W1**2*PHII1_Z) )
		    
		    DO IJ=1,6,DOFSYM
		      PSIM(IJ)=POTRADSLF(ISYM,IJ,N3,IFACSL)
    
		      PSIM_X(IJ)=VRADSLF(ISYM,1,IJ,N3,IFACSL)
		      PSIM_Y(IJ)=VRADSLF(ISYM,2,IJ,N3,IFACSL)
		      PSIM_Z(IJ)=VRADSLF(ISYM,3,IJ,N3,IFACSL)
		      
		      VS4BM= &
		      &    +1/(2.)*   (-ZI*W1*(PHI1_X*PSIM(IJ)+PHI1*PSIM_X(IJ))*CONJG(PHI2_X)		&
		      &                -ZI*W1*(PHI1_Y*PSIM(IJ)+PHI1*PSIM_Y(IJ))*CONJG(PHI2_Y)		&
		      &                +ZI*W2*(CONJG(PHI2_X)*PSIM(IJ)+CONJG(PHI2)*PSIM_X(IJ))*PHI1_X	&
		      &                +ZI*W2*(CONJG(PHI2_Y)*PSIM(IJ)+CONJG(PHI2)*PSIM_Y(IJ))*PHI1_Y)	&
		      &    -1/(2.)*   (-ZI*W1*(PHII1_X*PSIM(IJ)+PHII1*PSIM_X(IJ))*CONJG(PHII2_X)		&
		      &                -ZI*W1*(PHII1_Y*PSIM(IJ)+PHII1*PSIM_Y(IJ))*CONJG(PHII2_Y)		&
		      &                +ZI*W2*(CONJG(PHII2_X)*PSIM(IJ)+CONJG(PHII2)*PSIM_X(IJ))*PHII1_X	&
		      &                +ZI*W2*(CONJG(PHII2_Y)*PSIM(IJ)+CONJG(PHII2)*PSIM_Y(IJ))*PHII1_Y)
		      
		      
		      S1BM(IJ,N1,N2)=S1BM(IJ,N1,N2)+VS1BM*PSIM(IJ)*AIR
		      S4BM(IJ,N1,N2)=S4BM(IJ,N1,N2)+VS4BM*AIR
		    ENDDO
		ELSE
		      VS1BM=NAN
		      VS4BM=NAN
		      PSIM=NAN
		      PSIM_X=NAN
		      PSIM_Y=NAN
		      PSIM_Z=NAN
		      DO IJ=1,6,DOFSYM
		        S1BM(IJ,N1,N2)=NAN
		        S4BM(IJ,N1,N2)=NAN
		      ENDDO
		ENDIF
		
		IF (N4/=0) THEN
		      VS1BP=	+ ZI*(W1+W2)*				&
		      &                 (PHI1_X*PHI2_X+			&
		      &                  PHI1_Y*PHI2_Y+			&
		      &                  PHI1_Z*PHI2_Z-			&
		      &                  PHII1_X*PHII2_X-			&
		      &                  PHII1_Y*PHII2_Y-			&
		      &                  PHII1_Z*PHII2_Z )			&
		      &       +1/(2.*G)*  					&
		      &               (-ZI*W1*PHI1*(-W2**2*PHI2_Z)		&
		      &                -ZI*W2*PHI2*(-W1**2*PHI1_Z) )	&
		      &       -1/(2.*G)*  					&
		      &               (-ZI*W1*PHII1*(-W2**2*PHII2_Z)	&
		      &                -ZI*W2*PHII2*(-W1**2*PHII1_Z) )
		      
		      DO IJ=1,6,DOFSYM
			PSIP(IJ)=POTRADSLF(ISYM,IJ,N4,IFACSL)
	
			PSIP_X(IJ)=VRADSLF(ISYM,1,IJ,N4,IFACSL)
			PSIP_Y(IJ)=VRADSLF(ISYM,2,IJ,N4,IFACSL)
			PSIP_Z(IJ)=VRADSLF(ISYM,3,IJ,N4,IFACSL)
    
			VS4BP= &
			&    +1/(2.)*   (-ZI*W1*(PHI1_X*PSIP(IJ)+PHI1*PSIP_X(IJ))*PHI2_X		&
			&                -ZI*W1*(PHI1_Y*PSIP(IJ)+PHI1*PSIP_Y(IJ))*PHI2_Y		&
			&                -ZI*W2*(PHI2_X*PSIP(IJ)+PHI2*PSIP_X(IJ))*PHI1_X		&
			&                -ZI*W2*(PHI2_Y*PSIP(IJ)+PHI2*PSIP_Y(IJ))*PHI1_Y)		&
			&    -1/(2.)*   (-ZI*W1*(PHII1_X*PSIP(IJ)+PHII1*PSIP_X(IJ))*PHII2_X		&
			&                -ZI*W1*(PHII1_Y*PSIP(IJ)+PHII1*PSIP_Y(IJ))*PHII2_Y		&
			&                -ZI*W2*(PHII2_X*PSIP(IJ)+PHII2*PSIP_X(IJ))*PHII1_X		&
			&                -ZI*W2*(PHII2_Y*PSIP(IJ)+PHII2*PSIP_Y(IJ))*PHII1_Y)
			
			S1BP(IJ,N1,N2)=S1BP(IJ,N1,N2)+VS1BP*PSIP(IJ)*AIR
			S4BP(IJ,N1,N2)=S4BP(IJ,N1,N2)+VS4BP*AIR
		      ENDDO
		ELSE
		      VS1BP=NAN
		      VS4BP=NAN
		      PSIP=NAN
		      PSIP_X=NAN
		      PSIP_Y=NAN
		      PSIP_Z=NAN
		      DO IJ=1,6,DOFSYM
		        S1BP(IJ,N1,N2)=NAN
		        S4BP(IJ,N1,N2)=NAN
		      ENDDO
		ENDIF
		
		IF (Louthasfs==1) THEN
		  IF (N3/=0) THEN
		      VS1M=	+ ZI*(W1-W2)*					&
		      &                 (PHI1_X*CONJG(PHIP2_X)+		&
		      &                  PHI1_Y*CONJG(PHIP2_Y)+		&
		      &                  PHI1_Z*CONJG(PHIP2_Z)+		&
		      &                  PHIP1_X*CONJG(PHII2_X)+		&
		      &                  PHIP1_Y*CONJG(PHII2_Y)+		&
		      &                  PHIP1_Z*CONJG(PHII2_Z))
		      
		      VS2M=	- ZI*W1/(2.*G)*					&
		      &                 (PHI1 *(-W2**2*CONJG(PHIP2_Z))+	&
		      &                  PHIP1*(-W2**2*CONJG(PHII2_Z)) )
		      
		      VS3M=	+ ZI*W2/(2.*G)*					&
		      &                 (CONJG(PHI2 )*(-W1**2*(PHIP1_Z))+	&
		      &                  CONJG(PHIP2)*(-W1**2*(PHII1_Z)) )
		      
		      
		      DO IJ=1,6,DOFSYM
			VS4M=	-ZI*W1/2.*						&
			&    	( (PSIM_X(IJ)*PHI1+PHI1_X*PSIM(IJ)) * CONJG(PHIP2_X)+	&
			&    	  (PSIM_Y(IJ)*PHI1+PHI1_Y*PSIM(IJ)) * CONJG(PHIP2_Y) )
			
			VS5M=	-ZI*W1/2.*						&
			&    	( (PSIM_X(IJ)*PHIP1+PHIP1_X*PSIM(IJ)) * CONJG(PHII2_X)+	&
			&    	  (PSIM_Y(IJ)*PHIP1+PHIP1_Y*PSIM(IJ)) * CONJG(PHII2_Y) )
			
			VS6M=	+ZI*W2/2.*						&
			& ( (PSIM_X(IJ)*CONJG(PHI2)+CONJG(PHI2_X)*PSIM(IJ)) * PHIP1_X+	&
			&   (PSIM_Y(IJ)*CONJG(PHI2)+CONJG(PHI2_Y)*PSIM(IJ)) * PHIP1_Y )
			
			VS7M=	+ZI*W2/2.*						&
			& ( (PSIM_X(IJ)*CONJG(PHIP2)+CONJG(PHIP2_X)*PSIM(IJ)) * PHII1_X+	&
			&   (PSIM_Y(IJ)*CONJG(PHIP2)+CONJG(PHIP2_Y)*PSIM(IJ)) * PHII1_Y )
			
			
			S1M(IJ,N1,N2)=S1M(IJ,N1,N2)+VS1M*PSIM(IJ)*AIR
			S2M(IJ,N1,N2)=S2M(IJ,N1,N2)+VS2M*PSIM(IJ)*AIR
			S3M(IJ,N1,N2)=S3M(IJ,N1,N2)+VS3M*PSIM(IJ)*AIR
			
			S4M(IJ,N1,N2)=S4M(IJ,N1,N2)+VS4M*AIR
			S5M(IJ,N1,N2)=S5M(IJ,N1,N2)+VS5M*AIR
			S6M(IJ,N1,N2)=S6M(IJ,N1,N2)+VS6M*AIR
			S7M(IJ,N1,N2)=S7M(IJ,N1,N2)+VS7M*AIR
			
			IF (N1==NPRINTW1 .AND. N2==NPRINTW2 .AND. IJ==IJPRINT) THEN
			  INTLM_DZ  = -ZI*RHO*(W1-W2)/G*VS1BM*PSIM(IJ)
			  INTLM_DZZ = -ZI*RHO*(W1-W2)/G*VS4BM
			  IF (LQTFP==0) THEN
			    WRITE(128,*) XMSLF(IFACSL),(-1)**(ISYM-1)*YMSLF(IFACSL) &
			    & ,REAL(PHI1),AIMAG(PHI1),REAL(PHI1_X),AIMAG(PHI1_X),REAL(PHI1_Y),AIMAG(PHI1_Y),REAL(PHI1_Z),AIMAG(PHI1_Z) &
			    & ,REAL(PHII1),AIMAG(PHII1),REAL(PHII1_X),AIMAG(PHII1_X),REAL(PHII1_Y),AIMAG(PHII1_Y),REAL(PHII1_Z),AIMAG(PHII1_Z) &
			    & ,REAL(PHIP1),AIMAG(PHIP1),REAL(PHIP1_X),AIMAG(PHIP1_X),REAL(PHIP1_Y),AIMAG(PHIP1_Y),REAL(PHIP1_Z),AIMAG(PHIP1_Z) &
			    & ,REAL(PHI2),AIMAG(PHI2),REAL(PHI2_X),AIMAG(PHI2_X),REAL(PHI2_Y),AIMAG(PHI2_Y),REAL(PHI2_Z),AIMAG(PHI2_Z) &
			    & ,REAL(PHII2),AIMAG(PHII2),REAL(PHII2_X),AIMAG(PHII2_X),REAL(PHII2_Y),AIMAG(PHII2_Y),REAL(PHII2_Z),AIMAG(PHII2_Z) &
			    & ,REAL(PHIP2),AIMAG(PHIP2),REAL(PHIP2_X),AIMAG(PHIP2_X),REAL(PHIP2_Y),AIMAG(PHIP2_Y),REAL(PHIP2_Z),AIMAG(PHIP2_Z) &
			    & ,REAL(PSIM(IJ)),AIMAG(PSIM(IJ)),REAL(PSIM_X(IJ)),AIMAG(PSIM_X(IJ)),REAL(PSIM_Y(IJ)),AIMAG(PSIM_Y(IJ)),REAL(PSIM_Z(IJ)),AIMAG(PSIM_Z(IJ))
			    WRITE(122,*) XMSLF(IFACSL),(-1)**(ISYM-1)*YMSLF(IFACSL),REAL(INTLM_DZ ),AIMAG(INTLM_DZ )
			    WRITE(121,*) XMSLF(IFACSL),(-1)**(ISYM-1)*YMSLF(IFACSL),REAL(INTLM_DZZ),AIMAG(INTLM_DZZ)
			  ENDIF
			ENDIF
			
			
		      ENDDO
		  ELSE
			DO IJ=1,6,DOFSYM
			  S1M(IJ,N1,N2)=NAN
			  S2M(IJ,N1,N2)=NAN
			  S3M(IJ,N1,N2)=NAN
			  
			  S4M(IJ,N1,N2)=NAN
			  S5M(IJ,N1,N2)=NAN
			  S6M(IJ,N1,N2)=NAN
			  S7M(IJ,N1,N2)=NAN
			ENDDO
		  ENDIF
		  
		  IF (N4/=0) THEN
			VS1P=	+ ZI*(W1+W2)*				&
			&                 (PHI1_X*PHIP2_X+			&
			&                  PHI1_Y*PHIP2_Y+			&
			&                  PHI1_Z*PHIP2_Z+			&
			&                  PHIP1_X*PHII2_X+			&
			&                  PHIP1_Y*PHII2_Y+			&
			&                  PHIP1_Z*PHII2_Z)
			
			VS2P=	- ZI*W1/(2.*G)*				&
			&                 (PHI1 *(-W2**2*PHIP2_Z)+		&
			&                  PHIP1*(-W2**2*PHII2_Z) )
			
			VS3P=	- ZI*W2/(2.*G)*				&
			&                 (PHI2 *(-W1**2*(PHIP1_Z))+	&
			&                  PHIP2*(-W1**2*(PHII1_Z)) )
			
			DO IJ=1,6,DOFSYM
			  VS4P=	-ZI*W1/2.*					&
			  &    	( (PSIP_X(IJ)*PHI1+PHI1_X*PSIP(IJ)) * PHIP2_X+	&
			  &    	  (PSIP_Y(IJ)*PHI1+PHI1_Y*PSIP(IJ)) * PHIP2_Y )
			  
			  VS5P=	-ZI*W1/2.*					&
			  &    	( (PSIP_X(IJ)*PHIP1+PHIP1_X*PSIP(IJ)) * PHII2_X+&
			  &    	  (PSIP_Y(IJ)*PHIP1+PHIP1_Y*PSIP(IJ)) * PHII2_Y )
			  
			  VS6P=	-ZI*W2/2.*					&
			  &   	( (PSIP_X(IJ)*PHI2+PHI2_X*PSIP(IJ)) * PHIP1_X+	&
			  &   	  (PSIP_Y(IJ)*PHI2+PHI2_Y*PSIP(IJ)) * PHIP1_Y )
			  
			  VS7P=	-ZI*W2/2.*					&
			  &   	( (PSIP_X(IJ)*PHIP2+PHIP2_X*PSIP(IJ)) * PHII1_X+&
			  &   	  (PSIP_Y(IJ)*PHIP2+PHIP2_Y*PSIP(IJ)) * PHII1_Y )
			
			
			  S1P(IJ,N1,N2)=S1P(IJ,N1,N2)+VS1P*PSIP(IJ)*AIR
			  S2P(IJ,N1,N2)=S2P(IJ,N1,N2)+VS2P*PSIP(IJ)*AIR
			  S3P(IJ,N1,N2)=S3P(IJ,N1,N2)+VS3P*PSIP(IJ)*AIR
			  
			  S4P(IJ,N1,N2)=S4P(IJ,N1,N2)+VS4P*AIR
			  S5P(IJ,N1,N2)=S5P(IJ,N1,N2)+VS5P*AIR
			  S6P(IJ,N1,N2)=S6P(IJ,N1,N2)+VS6P*AIR
			  S7P(IJ,N1,N2)=S7P(IJ,N1,N2)+VS7P*AIR
			  
			  
			  IF (N1==NPRINTW1 .AND. N2==NPRINTW2 .AND. IJ==IJPRINT) THEN
			    INTLP_DZ  = -ZI*RHO*(W1+W2)/G*VS1BP*PSIP(IJ)
			    INTLP_DZZ = -ZI*RHO*(W1+W2)/G*VS4BP
			    
			    WRITE(128,*) XMSLF(IFACSL),(-1)**(ISYM-1)*YMSLF(IFACSL) &
			    & ,REAL(PHI1 ),AIMAG(PHI1 ),REAL(PHI1_X ),AIMAG(PHI1_X ),REAL(PHI1_Y ),AIMAG(PHI1_Y ),REAL(PHI1_Z ),AIMAG(PHI1_Z ) &
			    & ,REAL(PHII1),AIMAG(PHII1),REAL(PHII1_X),AIMAG(PHII1_X),REAL(PHII1_Y),AIMAG(PHII1_Y),REAL(PHII1_Z),AIMAG(PHII1_Z) &
			    & ,REAL(PHIP1),AIMAG(PHIP1),REAL(PHIP1_X),AIMAG(PHIP1_X),REAL(PHIP1_Y),AIMAG(PHIP1_Y),REAL(PHIP1_Z),AIMAG(PHIP1_Z) &
			    & ,REAL(PHI2 ),AIMAG(PHI2 ),REAL(PHI2_X ),AIMAG(PHI2_X ),REAL(PHI2_Y ),AIMAG(PHI2_Y ),REAL(PHI2_Z ),AIMAG(PHI2_Z ) &
			    & ,REAL(PHII2),AIMAG(PHII2),REAL(PHII2_X),AIMAG(PHII2_X),REAL(PHII2_Y),AIMAG(PHII2_Y),REAL(PHII2_Z),AIMAG(PHII2_Z) &
			    & ,REAL(PHIP2),AIMAG(PHIP2),REAL(PHIP2_X),AIMAG(PHIP2_X),REAL(PHIP2_Y),AIMAG(PHIP2_Y),REAL(PHIP2_Z),AIMAG(PHIP2_Z) &
			    & ,REAL(PSIM(IJ)),AIMAG(PSIM(IJ)),REAL(PSIM_X(IJ)),AIMAG(PSIM_X(IJ)),REAL(PSIM_Y(IJ)),AIMAG(PSIM_Y(IJ)),REAL(PSIM_Z(IJ)),AIMAG(PSIM_Z(IJ)) &
			    & ,REAL(PSIP(IJ)),AIMAG(PSIP(IJ)),REAL(PSIP_X(IJ)),AIMAG(PSIP_X(IJ)),REAL(PSIP_Y(IJ)),AIMAG(PSIP_Y(IJ)),REAL(PSIP_Z(IJ)),AIMAG(PSIP_Z(IJ)) 
			    WRITE(122,*) XMSLF(IFACSL),(-1)**(ISYM-1)*YMSLF(IFACSL),REAL(INTLM_DZ ),AIMAG(INTLM_DZ ),REAL(INTLP_DZ ),AIMAG(INTLP_DZ )
			    WRITE(121,*) XMSLF(IFACSL),(-1)**(ISYM-1)*YMSLF(IFACSL),REAL(INTLM_DZZ),AIMAG(INTLM_DZZ),REAL(INTLP_DZZ),AIMAG(INTLP_DZZ)
			  ENDIF
			  
			  
			ENDDO
		  ELSE
			DO IJ=1,6,DOFSYM
			  S1P(IJ,N1,N2)=NAN
			  S2P(IJ,N1,N2)=NAN
			  S3P(IJ,N1,N2)=NAN
			  
			  S4P(IJ,N1,N2)=NAN
			  S5P(IJ,N1,N2)=NAN
			  S6P(IJ,N1,N2)=NAN
			  S7P(IJ,N1,N2)=NAN
			ENDDO
		  ENDIF
		ENDIF
        !!!!!!!!!!!                                                                        !!!!!!!!!!!
        !!!!    -I(W1-W2)(GRAD PHI1 GRAD PHIP2* + GRAD PHIP1 GRAD PHII2) PSIM(IJ) DS  !!!!!
        !!!!!!!!!!!                                                                         !!!!!!!!!!

		AI=AI+AIR
	    210 END DO
	    
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	    
	    DO IJ=1,6,DOFSYM  !DEGRE DE LIBERTE
		IF (N3/=0) E1BM(IJ,N1,N2)=CMPLX(0.,0.)
		IF (N4/=0) E1BP(IJ,N1,N2)=CMPLX(0.,0.)
		
		
		IF (Louthasfs==1) THEN
		  IF (N3/=0) THEN
		    E1M(IJ,N1,N2)=CMPLX(0.,0.)
		    E2M(IJ,N1,N2)=CMPLX(0.,0.)
		    E3M(IJ,N1,N2)=CMPLX(0.,0.)
		    E4M(IJ,N1,N2)=CMPLX(0.,0.)
		  ENDIF
		  IF (N4/=0) THEN
		    E1P(IJ,N1,N2)=CMPLX(0.,0.)
		    E2P(IJ,N1,N2)=CMPLX(0.,0.)
		    E3P(IJ,N1,N2)=CMPLX(0.,0.)
		    E4P(IJ,N1,N2)=CMPLX(0.,0.)
		  ENDIF
		ENDIF
	    ENDDO
	    
	    
	    

	    LONGCONT=0
	    DO 211 IFACSL=1,NCONT
	      DO 211 ISYM=1,NJ
                PHI1 =POTTOTSLC(ISYM,N1,IFACSL)
                PHIP1=POTPERSLC(ISYM,N1,IFACSL)
                PHII1=POTINCSLC(ISYM,N1,IFACSL)

                PHI2 =POTTOTSLC(ISYM,N2,IFACSL)
		PHIP2=POTPERSLC(ISYM,N2,IFACSL)
                PHII2=POTINCSLC(ISYM,N2,IFACSL)

                PHI1_X =VTOTSLC(ISYM,1,N1,IFACSL)
                PHIP1_X=VPERSLC(ISYM,1,N1,IFACSL)
                PHII1_X=VINCSLC(ISYM,1,N1,IFACSL)

                PHI1_Y =VTOTSLC(ISYM,2,N1,IFACSL)
                PHIP1_Y=VPERSLC(ISYM,2,N1,IFACSL)
                PHII1_Y=VINCSLC(ISYM,2,N1,IFACSL)

                PHI1_Z =VTOTSLC(ISYM,3,N1,IFACSL)
                PHIP1_Z=VPERSLC(ISYM,3,N1,IFACSL)
                PHII1_Z=VINCSLC(ISYM,3,N1,IFACSL)

                PHI2_X =VTOTSLC(ISYM,1,N2,IFACSL)
                PHIP2_X=VPERSLC(ISYM,1,N2,IFACSL)
                PHII2_X=VINCSLC(ISYM,1,N2,IFACSL)

                PHI2_Y =VTOTSLC(ISYM,2,N2,IFACSL)
                PHIP2_Y=VPERSLC(ISYM,2,N2,IFACSL)
                PHII2_Y=VINCSLC(ISYM,2,N2,IFACSL)

                PHI2_Z =VTOTSLC(ISYM,3,N2,IFACSL)
                PHIP2_Z=VPERSLC(ISYM,3,N2,IFACSL)
                PHII2_Z=VINCSLC(ISYM,3,N2,IFACSL)
                
                AIR=AIRESLC(IFACSL)
                LONG=SQRT(XMSLC(IFACSL)**2+YMSLC(IFACSL)**2)

	    ! EiP/M	: INTEGRALE SUR LA LIGNE DE FLOTTAISON (ISSUE DES DERIVEE SECONDE)
	    ! E1BP/M 	: FORMULATION DES INTEGRALE ISSUE DU PAPIER 
	    !			E1BP/M = E1P/M + E2P/M + E3P/M + E4P/M
                CNY=CNSLC(2,IFACSL)*(-1)**(ISYM+1)
                CNX=CNSLC(1,IFACSL)
		
		IF (N3/=0) THEN
		    VARCONTM= 									&
		    &	( + ZI*W1/2.*(CONJG(PHI2_X )*CNX+CONJG(PHI2_Y )*CNY)*      PHI1		&
		    &	  - ZI*W2/2.*(      PHI1_X  *CNX+      PHI1_Y  *CNY)*CONJG(PHI2 )	&
		    &	  - ZI*W1/2.*(CONJG(PHII2_X)*CNX+CONJG(PHII2_Y)*CNY)*      PHII1	&
		    &	  + ZI*W2/2.*(      PHII1_X *CNX+      PHII1_Y *CNY)*CONJG(PHII2) )
		    
		    DO IJ=1,6,DOFSYM  !DEGRE DE LIBERTE
		      PSIM(IJ)  =POTRADSLC(ISYM,IJ,N3,IFACSL)
		      E1BM(IJ,N1,N2)=E1BM(IJ,N1,N2)+VARCONTM*PSIM(IJ)*AIR
		    ENDDO
		ELSE
		    DO IJ=1,6,DOFSYM  !DEGRE DE LIBERTE
			PSIM(IJ)=NAN
			E1BM(IJ,N1,N2)=NAN
		    ENDDO
		ENDIF
		IF (N4/=0) THEN
		      VARCONTP= 							&
		      &            ( + ZI*W1/2.*(PHI2_X *CNX+PHI2_Y *CNY)*PHI1 	&
		      &              + ZI*W2/2.*(PHI1_X *CNX+PHI1_Y *CNY)*PHI2  	&
		      &              - ZI*W1/2.*(PHII2_X*CNX+PHII2_Y*CNY)*PHII1	&
		      &              - ZI*W2/2.*(PHII1_X*CNX+PHII1_Y*CNY)*PHII2 )
		      DO IJ=1,6,DOFSYM  !DEGRE DE LIBERTE
			PSIP(IJ)=POTRADSLC(ISYM,IJ,N4,IFACSL)
			E1BP(IJ,N1,N2)=E1BP(IJ,N1,N2)+VARCONTP*PSIP(IJ)*AIR
		      ENDDO
		ELSE
		      DO IJ=1,6,DOFSYM  !DEGRE DE LIBERTE
			PSIP(IJ)=NAN
			E1BP(IJ,N1,N2)=NAN
		      ENDDO
		ENDIF
		
		IF (Louthasfs==1) THEN
		  IF (N3/=0) THEN
		      VE1M= + ZI*W1/2.*( CONJG(PHIP2_X)*CNX + CONJG(PHIP2_Y)*CNY )*PHI1
		      VE2M= + ZI*W1/2.*( CONJG(PHII2_X)*CNX + CONJG(PHII2_Y)*CNY )*PHIP1
		      VE3M= - ZI*W2/2.*( PHIP1_X*CNX + PHIP1_Y*CNY )*CONJG(PHI2)
		      VE4M= - ZI*W2/2.*( PHII1_X*CNX + PHII1_Y*CNY )*CONJG(PHIP2)
		      DO IJ=1,6,DOFSYM
			E1M(IJ,N1,N2)=E1M(IJ,N1,N2)+VE1M*PSIM(IJ)*AIR
			E2M(IJ,N1,N2)=E2M(IJ,N1,N2)+VE2M*PSIM(IJ)*AIR
			E3M(IJ,N1,N2)=E3M(IJ,N1,N2)+VE3M*PSIM(IJ)*AIR
			E4M(IJ,N1,N2)=E4M(IJ,N1,N2)+VE4M*PSIM(IJ)*AIR
			
			IF (N1==NPRINTW1 .AND. N2==NPRINTW2 .AND. IJ==IJPRINT .AND. N4==0) THEN
              WRITE(178,*) XMSLC(IFACSL),(-1)**(ISYM-1)*YMSLC(IFACSL),CNX,CNY,REAL(VARCONTM*PSIM(IJ)),AIMAG(VARCONTM*PSIM(IJ))
			ENDIF
			
		      ENDDO
		  ELSE
		      DO IJ=1,6,DOFSYM
			E1M(IJ,N1,N2)=NAN
			E2M(IJ,N1,N2)=NAN
			E3M(IJ,N1,N2)=NAN
			E4M(IJ,N1,N2)=NAN
		      ENDDO
		  ENDIF
		  IF (N4/=0) THEN
			VE1P= + ZI*W1/2.*( PHIP2_X*CNX + PHIP2_Y*CNY )*PHI1
			VE2P= + ZI*W1/2.*( PHII2_X*CNX + PHII2_Y*CNY )*PHIP1
			VE3P= + ZI*W2/2.*( PHIP1_X*CNX + PHIP1_Y*CNY )*PHI2
			VE4P= + ZI*W2/2.*( PHII1_X*CNX + PHII1_Y*CNY )*PHIP2
			DO IJ=1,6,DOFSYM
			  E1P(IJ,N1,N2)=E1P(IJ,N1,N2)+VE1P*PSIP(IJ)*AIR
			  E2P(IJ,N1,N2)=E2P(IJ,N1,N2)+VE2P*PSIP(IJ)*AIR
			  E3P(IJ,N1,N2)=E3P(IJ,N1,N2)+VE3P*PSIP(IJ)*AIR
			  E4P(IJ,N1,N2)=E4P(IJ,N1,N2)+VE4P*PSIP(IJ)*AIR
			  
			  IF (N1==NPRINTW1 .AND. N2==NPRINTW2 .AND. IJ==IJPRINT) THEN
			    WRITE(178,*) XMSLC(IFACSL),(-1)**(ISYM-1)*YMSLC(IFACSL),CNX,CNY &
                & ,REAL(VARCONTM*PSIM(IJ)),AIMAG(VARCONTM*PSIM(IJ)),REAL(VARCONTP*PSIP(IJ)),AIMAG(VARCONTP*PSIP(IJ))
			  ENDIF
			  
			ENDDO
		  ELSE
			DO IJ=1,6,DOFSYM
			  E1P(IJ,N1,N2)=NAN
			  E2P(IJ,N1,N2)=NAN
			  E3P(IJ,N1,N2)=NAN
			  E4P(IJ,N1,N2)=NAN
			ENDDO
		  ENDIF
		ENDIF
		LONGCONT=LONGCONT+AIR
		
		
	    211 ENDDO
	    IF (ICER==1 .AND. N1==NPRINTW1 .AND. N2==NPRINTW2) THEN
      !!!!!!! pour avoir une idee de la variation radiale !!!!!
		DO 212 IFACSL=1,NLIGNE
		    PHI1=POTTOTSLL(1,N1,IFACSL)
		    PHIP1=POTPERSLL(1,N1,IFACSL)
		    PHII1=POTINCSLL(1,N1,IFACSL)
    
		    PHI2=POTTOTSLL(1,N2,IFACSL)
		    PHIP2=POTPERSLL(1,N2,IFACSL)
		    PHII2=POTINCSLL(1,N2,IFACSL)
    
		    PHI1_X=VTOTSLL(1,1,N1,IFACSL)
		    PHIP1_X=VPERSLL(1,1,N1,IFACSL)
		    PHII1_X=VINCSLL(1,1,N1,IFACSL)
    
		    PHI1_Y=VTOTSLL(1,2,N1,IFACSL)
		    PHIP1_Y=VPERSLL(1,2,N1,IFACSL)
		    PHII1_Y=VINCSLL(1,2,N1,IFACSL)
    
		    PHI1_Z=VTOTSLL(1,3,N1,IFACSL)
		    PHIP1_Z=VPERSLL(1,3,N1,IFACSL)
		    PHII1_Z=VINCSLL(1,3,N1,IFACSL)
    
		    PHI2_X=VTOTSLL(1,1,N2,IFACSL)
		    PHIP2_X=VPERSLL(1,1,N2,IFACSL)
		    PHII2_X=VINCSLL(1,1,N2,IFACSL)
    
		    PHI2_Y=VTOTSLL(1,2,N2,IFACSL)
		    PHIP2_Y=VPERSLL(1,2,N2,IFACSL)
		    PHII2_Y=VINCSLL(1,2,N2,IFACSL)
    
		    PHI2_Z=VTOTSLL(1,3,N2,IFACSL)
		    PHIP2_Z=VPERSLL(1,3,N2,IFACSL)
		    PHII2_Z=VINCSLL(1,3,N2,IFACSL)
		    
		    IF (N3/=0) THEN
			PSIM(IJPRINT)=POTRADSLL(1,IJPRINT,N3,IFACSL)
	
			PSIM_X(IJPRINT)=VRADSLL(1,1,IJPRINT,N3,IFACSL)
			PSIM_Y(IJPRINT)=VRADSLL(1,2,IJPRINT,N3,IFACSL)
			PSIM_Z(IJPRINT)=VRADSLL(1,3,IJPRINT,N3,IFACSL)
		    ELSE
			PSIM(IJPRINT)=0.
			PSIM_X(IJPRINT)=0.
			PSIM_Y(IJPRINT)=0.
			PSIM_Z(IJPRINT)=0.
		    ENDIF
		    IF (N4/=0) THEN
			PSIP(IJPRINT)=POTRADSLL(1,IJPRINT,N4,IFACSL)
	
			PSIP_X(IJPRINT)=VRADSLL(1,1,IJPRINT,N4,IFACSL)
			PSIP_Y(IJPRINT)=VRADSLL(1,2,IJPRINT,N4,IFACSL)
			PSIP_Z(IJPRINT)=VRADSLL(1,3,IJPRINT,N4,IFACSL)
		    ELSE
			PSIP(IJPRINT)=0
			PSIP_X(IJPRINT)=0
			PSIP_Y(IJPRINT)=0
			PSIP_Z(IJPRINT)=0
		    ENDIF
    
		    IF (N4==0) THEN
				WRITE(130,*) XMSLL(IFACSL),XMSLL(IFACSL) &
				& ,REAL(PHI1 ),AIMAG(PHI1 ),REAL(PHI1_X ),AIMAG(PHI1_X ),REAL(PHI1_Y ),AIMAG(PHI1_Y ),REAL(PHI1_Z ),AIMAG(PHI1_Z ) &
				& ,REAL(PHII1),AIMAG(PHII1),REAL(PHII1_X),AIMAG(PHII1_X),REAL(PHII1_Y),AIMAG(PHII1_Y),REAL(PHII1_Z),AIMAG(PHII1_Z) &
				& ,REAL(PHIP1),AIMAG(PHIP1),REAL(PHIP1_X),AIMAG(PHIP1_X),REAL(PHIP1_Y),AIMAG(PHIP1_Y),REAL(PHIP1_Z),AIMAG(PHIP1_Z) &
				& ,REAL(PHI2 ),AIMAG(PHI2 ),REAL(PHI2_X ),AIMAG(PHI2_X ),REAL(PHI2_Y ),AIMAG(PHI2_Y ),REAL(PHI2_Z ),AIMAG(PHI2_Z ) &
				& ,REAL(PHII2),AIMAG(PHII2),REAL(PHII2_X),AIMAG(PHII2_X),REAL(PHII2_Y),AIMAG(PHII2_Y),REAL(PHII2_Z),AIMAG(PHII2_Z) &
				& ,REAL(PHIP2),AIMAG(PHIP2),REAL(PHIP2_X),AIMAG(PHIP2_X),REAL(PHIP2_Y),AIMAG(PHIP2_Y),REAL(PHIP2_Z),AIMAG(PHIP2_Z) &
				& ,REAL(PSIM(IJPRINT)),AIMAG(PSIM(IJPRINT)),REAL(PSIM_X(IJPRINT)),AIMAG(PSIM_X(IJPRINT)),REAL(PSIM_Y(IJPRINT)),AIMAG(PSIM_Y(IJPRINT)),REAL(PSIM_Z(IJPRINT)),AIMAG(PSIM_Z(IJPRINT))
		    ELSE 
				WRITE(130,*) XMSLL(IFACSL),XMSLL(IFACSL) &
				& ,REAL(PHI1 ),AIMAG(PHI1 ),REAL(PHI1_X ),AIMAG(PHI1_X ),REAL(PHI1_Y ),AIMAG(PHI1_Y ),REAL(PHI1_Z ),AIMAG(PHI1_Z ) &
				& ,REAL(PHII1),AIMAG(PHII1),REAL(PHII1_X),AIMAG(PHII1_X),REAL(PHII1_Y),AIMAG(PHII1_Y),REAL(PHII1_Z),AIMAG(PHII1_Z) &
				& ,REAL(PHIP1),AIMAG(PHIP1),REAL(PHIP1_X),AIMAG(PHIP1_X),REAL(PHIP1_Y),AIMAG(PHIP1_Y),REAL(PHIP1_Z),AIMAG(PHIP1_Z) &
				& ,REAL(PHI2 ),AIMAG(PHI2 ),REAL(PHI2_X ),AIMAG(PHI2_X ),REAL(PHI2_Y ),AIMAG(PHI2_Y ),REAL(PHI2_Z ),AIMAG(PHI2_Z ) &
				& ,REAL(PHII2),AIMAG(PHII2),REAL(PHII2_X),AIMAG(PHII2_X),REAL(PHII2_Y),AIMAG(PHII2_Y),REAL(PHII2_Z),AIMAG(PHII2_Z) &
				& ,REAL(PHIP2),AIMAG(PHIP2),REAL(PHIP2_X),AIMAG(PHIP2_X),REAL(PHIP2_Y),AIMAG(PHIP2_Y),REAL(PHIP2_Z),AIMAG(PHIP2_Z) &
				& ,REAL(PSIM(IJPRINT)),AIMAG(PSIM(IJPRINT)),REAL(PSIM_X(IJPRINT)),AIMAG(PSIM_X(IJPRINT)),REAL(PSIM_Y(IJPRINT)),AIMAG(PSIM_Y(IJPRINT)),REAL(PSIM_Z(IJPRINT)),AIMAG(PSIM_Z(IJPRINT)) &
				& ,REAL(PSIP(IJPRINT)),AIMAG(PSIP(IJPRINT)),REAL(PSIP_X(IJPRINT)),AIMAG(PSIP_X(IJPRINT)),REAL(PSIP_Y(IJPRINT)),AIMAG(PSIP_Y(IJPRINT)),REAL(PSIP_Z(IJPRINT)),AIMAG(PSIP_Z(IJPRINT)) 
		    ENDIF
		212 ENDDO
	    ENDIF

		
        !!!!!!SOMMATION ET ENREGISTREMENT!!!!!!!!
    DO 201 IJ=1,6,DOFSYM  !DEGRE DE LIBERTE
	IF (N3/=0) THEN
	    CONTRIBM(1,IJ,N1,N2)=-ZI*RHO*(W1-W2)/G*(S1BM(IJ,N1,N2))!S1M(IJ)+S2M(IJ)+S3M(IJ)
	    CONTRIBM(2,IJ,N1,N2)=-ZI*RHO*(W1-W2)/G*(S4BM(IJ,N1,N2))!S4M(IJ)+S5M(IJ)+S6M(IJ)+S7M(IJ))
	    CONTRIBM(3,IJ,N1,N2)=-ZI*RHO*(W1-W2)/G*(E1BM(IJ,N1,N2))!E1M(IJ)+E2M(IJ)+E3M(IJ)+E4M(IJ))
	    EFFM(IJ,N1,N2,ICER)=&
	    & CONTRIBM(1,IJ,N1,N2)&
	    &+CONTRIBM(2,IJ,N1,N2)&
	    &+CONTRIBM(3,IJ,N1,N2)
	ELSE
	    CONTRIBM(1,IJ,N1,N2)=0.
	    CONTRIBM(2,IJ,N1,N2)=0.
	    CONTRIBM(3,IJ,N1,N2)=0.
	    EFFM(IJ,N1,N2,ICER)=0.
	ENDIF
	IF (N4/=0) THEN
	    CONTRIBP(1,IJ,N1,N2)=-ZI*RHO*(W1+W2)/G*(S1BP(IJ,N1,N2))!S1M(IJ)+S2M(IJ)+S3M(IJ)
	    CONTRIBP(2,IJ,N1,N2)=-ZI*RHO*(W1+W2)/G*(S4BP(IJ,N1,N2))!S4M(IJ)+S5M(IJ)+S6M(IJ)+S7M(IJ))
	    CONTRIBP(3,IJ,N1,N2)=-ZI*RHO*(W1+W2)/G*(E1BP(IJ,N1,N2))!E1M(IJ)+E2M(IJ)+E3M(IJ)+E4M(IJ))
	    EFFP(IJ,N1,N2,ICER)=&
	    & CONTRIBP(1,IJ,N1,N2)&
	    &+CONTRIBP(2,IJ,N1,N2)&
	    &+CONTRIBP(3,IJ,N1,N2)
	ENDIF
	
	IF(N1==NPRINTW1 .AND. N2==NPRINTW2 .AND. IJ==IJPRINT .AND. Louthasfs==1 ) THEN
	  IF (N3/=0) THEN
	      EFFSM=-ZI*RHO*(W1-W2)/G*(S1M(IJ,N1,N2)+S2M(IJ,N1,N2)+S3M(IJ,N1,N2) 	&
	      & +S4M(IJ,N1,N2)+S5M(IJ,N1,N2)+S6M(IJ,N1,N2)+S7M(IJ,N1,N2)		&
	      & +E1M(IJ,N1,N2)+E2M(IJ,N1,N2)+E3M(IJ,N1,N2)+E4M(IJ,N1,N2))
	  ELSE
	      EFFSM=0.
	  ENDIF
	  IF (N4/=0) THEN
	    EFFSP=-ZI*RHO*(W1+W2)/G*(S1P(IJ,N1,N2)+S2P(IJ,N1,N2)+S3P(IJ,N1,N2)	&
	    & +S4P(IJ,N1,N2)+S5P(IJ,N1,N2)+S6P(IJ,N1,N2)+S7P(IJ,N1,N2)		&
	    & +E1P(IJ,N1,N2)+E2P(IJ,N1,N2)+E3P(IJ,N1,N2)+E4P(IJ,N1,N2))

	    WRITE(137,*) RCER(ICER),REAL(CONTRIBM(1,IJ,N1,N2)),AIMAG(CONTRIBM(1,IJ,N1,N2)),REAL(CONTRIBP(1,IJ,N1,N2)),AIMAG(CONTRIBP(1,IJ,N1,N2))
	    WRITE(138,*) RCER(ICER),REAL(CONTRIBM(2,IJ,N1,N2)),AIMAG(CONTRIBM(2,IJ,N1,N2)),REAL(CONTRIBP(2,IJ,N1,N2)),AIMAG(CONTRIBP(2,IJ,N1,N2))
	    WRITE(134,*) RCER(ICER),REAL(CONTRIBM(3,IJ,N1,N2)),AIMAG(CONTRIBM(3,IJ,N1,N2)),REAL(CONTRIBP(3,IJ,N1,N2)),AIMAG(CONTRIBP(3,IJ,N1,N2))
	    WRITE(132,*) RCER(ICER),REAL(EFFSM),AIMAG(EFFSM),REAL(EFFSP),AIMAG(EFFSP)
	    
	  ELSE
	  
	    WRITE(137,*) RCER(ICER),REAL(CONTRIBM(1,IJ,N1,N2)),AIMAG(CONTRIBM(1,IJ,N1,N2))
	    WRITE(138,*) RCER(ICER),REAL(CONTRIBM(2,IJ,N1,N2)),AIMAG(CONTRIBM(2,IJ,N1,N2))
	    WRITE(134,*) RCER(ICER),REAL(CONTRIBM(3,IJ,N1,N2)),AIMAG(CONTRIBM(3,IJ,N1,N2))
	    WRITE(132,*) RCER(ICER),REAL(EFFSM),AIMAG(EFFSM)

	  ENDIF  
	ENDIF
	

        

        TABW(N2)=W2
        TABW(N1)=W1


201     END DO!FIN BOUCLE SUR LES DOF
200 END DO!FIN DE BOUCLE SUR LES PULSATIONS
    ELSE 
	WRITE(*,*)   'NTHETA = ',NTHETA
	WRITE(*,*)   'INDCONT = ',INDCONT
	WRITE(*,*)   'IRCER = ',IRCER(ICER)
	WRITE(*,*)   'RCER = ',RCER(ICER)*COS(PI/NJ/NTHETA)
	WRITE(*,*)   'R1 = ',R1,'R2 = ',R2,'DR =',DR
	WRITE(*,*)   'RC1 = ',RC1,'RC2 = ',RC2,'DRC = ',DRC
    ENDIF
215 END DO



    IF ( Louthasfs==1 ) THEN
      CLOSE(178)
      CLOSE(128)
      CLOSE(122)
      CLOSE(121)
      CLOSE(130)
      CLOSE(138)
      CLOSE(139)
      CLOSE(134)
      CLOSE(131)
      CLOSE(132)
      CLOSE(133)
      IF (LQTFP .EQ. 1) THEN
	  CLOSE(134)
	  CLOSE(135)
      ENDIF
    ENDIF
    
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    PRINT *, ''
    PRINT *,'CALCULS SUR LA PARTIE EXACTE TERMINEE'
    
    
    WRITE(*,*) 'QTF- CALCULEES POUR W- = 0 --> ',TABW(N-1)
    IF (LQTFP==1) THEN
        WRITE(*,*) 'QTF+ CALCULEES POUR W+ = ',TABW(2),' --> ',TABW(N)
    ENDIF




!!!!!!!CONVERGENCE DU TERME A INTEGRER!!!!
!! ON SE PLACE SUR LE MAILLAGE LIGNE DEFINI PRECEDEMENT, L'AIRE EST EGALE A LA DISTANCE ENTRE DEUX POINTS!

    DO IJ=1,6,DOFSYM
	WRITE(FMTV,'(I1)')IJ
	OPEN(124,FILE=ID(1:lID)//'/results/QTF/QTFM_HASFS_DOF_'//TRIM(FMTV)//'_PR.dat')
	OPEN(125,FILE=ID(1:lID)//'/results/QTF/QTFM_HASFS_DOF_'//TRIM(FMTV)//'_PI.dat')
	IF (LQTFP .EQ. 1) THEN		    
	    OPEN(126,FILE=ID(1:lID)//'/results/QTF/QTFP_HASFS_DOF_'//TRIM(FMTV)//'_PR.dat')
	    OPEN(127,FILE=ID(1:lID)//'/results/QTF/QTFP_HASFS_DOF_'//TRIM(FMTV)//'_PI.dat')
	ENDIF

!!!!!!! Permet de sortir les QTF à chaque rayons -> PAS UTILE
! 	DO 1984 ICER=1,NRCER
	
! !!!!!!!!!!!!!! version matrice carre pour les QTF+!!!!!!!!!!!!!!!!!!!!!!
! !~ 	    WRITE(124,1989) RCER(ICER),(TABW(I1),I1=1,NHASKIND)
! !~ 	    WRITE(125,1989) RCER(ICER),(TABW(I1),I1=1,NHASKIND)
! !~ 	    IF (LQTFP .EQ. 1) THEN
! !~ 		WRITE(126,1988) RCER(ICER),(TABW(I1),I1=1,NHASKIND)
! !~ 		WRITE(127,1988) RCER(ICER),(TABW(I1),I1=1,NHASKIND)
! !~ 	    ENDIF
! !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

! !!! version matrice antitriangulaire sup pour les QTF+ (0 ailleurs)!!!!!
! 	    WRITE(124,1989) RCER(ICER),(TABW(I1),I1=1,N)
! 	    WRITE(125,1989) RCER(ICER),(TABW(I1),I1=1,N)
! 	    IF (LQTFP .EQ. 1) THEN
! 		WRITE(126,1988) RCER(ICER),(TABW(I1),I1=1,N)
! 		WRITE(127,1988) RCER(ICER),(TABW(I1),I1=1,N)
! 	    ENDIF
! !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
! !~ 	    DO 1984 I1=1,NHASKIND					! version matrice carre pour les QTF+
! 	    DO 1984 I1=1,N						! version matrice antitriangulaire sup pour les QTF+ (0 ailleurs)
	    
! !!!!!!!!!!!!!! version matrice carre pour les QTF+!!!!!!!!!!!!!!!!!!!!!!
! !~ 		!!!  QTFij-=QTFji-* !!!
! !~ 		! ON PREND LE CONJUGE DU TRIANGLE SUP
! !~ 		WRITE(124,1991)TABW(I1),(REAL(EFFM(IJ,I1,I2,ICER)),I2=1,I1-1),0.,(REAL(EFFM(IJ,I2,I1,ICER)),I2=I1+1,NHASKIND)
! !~ 		WRITE(125,1991)TABW(I1),(AIMAG(EFFM(IJ,I1,I2,ICER)),I2=1,I1-1),0.,(-AIMAG(EFFM(IJ,I2,I1,ICER)),I2=I1+1,NHASKIND)
! !~ 		IF (LQTFP .EQ. 1) THEN
! !~ 		    !!!  QTFij+=QTFji+ !!!
! !~ 		    WRITE(126,1991)TABW(I1),(REAL(EFFP(IJ,I1,I2,ICER)),I2=1,I1-1),0.,(REAL(EFFP(IJ,I2,I1,ICER)),I2=I1+1,NHASKIND)
! !~ 		    WRITE(127,1991)TABW(I1),(AIMAG(EFFP(IJ,I1,I2,ICER)),I2=1,I1-1),0.,(AIMAG(EFFP(IJ,I2,I1,ICER)),I2=I1+1,NHASKIND)
! !~ 		ENDIF
! !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

! !!! version matrice antitriangulaire sup pour les QTF+ (0 ailleurs)!!!!!
! 		!!!  QTFij-=QTFji-* !!!
! 		! ON PREND LE CONJUGE DU TRIANGLE SUP
! 		WRITE(124,1991)TABW(I1),(REAL(EFFM(IJ,I1,I2,ICER)),I2=1,I1-1),0.,(REAL(EFFM(IJ,I2,I1,ICER)),I2=I1+1,N)
! 		WRITE(125,1991)TABW(I1),(AIMAG(EFFM(IJ,I1,I2,ICER)),I2=1,I1-1),0.,(-AIMAG(EFFM(IJ,I2,I1,ICER)),I2=I1+1,N)
! 		IF (LQTFP .EQ. 1) THEN
! 		    !!!  QTFij+=QTFji+ !!!
! 		    WRITE(126,1991)TABW(I1),(REAL(EFFP(IJ,I1,I2,ICER)),I2=1,I1),(REAL(EFFP(IJ,I2,I1,ICER)),I2=I1+1,N)
! 		    WRITE(127,1991)TABW(I1),(AIMAG(EFFP(IJ,I1,I2,ICER)),I2=1,I1),(AIMAG(EFFP(IJ,I2,I1,ICER)),I2=I1+1,N)
! 		ENDIF
! !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
! 	1984 END DO

!!!!!!! Ecrire les QTF que pour RMAX -> ICER = NRCER

!!!!!!!!!!!!!! version matrice carre pour les QTF+!!!!!!!!!!!!!!!!!!!!!!
!~        WRITE(124,1989) RCER(ICER),(TABW(I1),I1=1,NHASKIND)
!~        WRITE(125,1989) RCER(ICER),(TABW(I1),I1=1,NHASKIND)
!~        IF (LQTFP .EQ. 1) THEN
!~        WRITE(126,1988) RCER(ICER),(TABW(I1),I1=1,NHASKIND)
!~        WRITE(127,1988) RCER(ICER),(TABW(I1),I1=1,NHASKIND)
!~        ENDIF
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

!!! version matrice antitriangulaire sup pour les QTF+ (0 ailleurs)!!!!!
      WRITE(124,1989) RCER(NRCER),(TABW(I1),I1=1,N)
      WRITE(125,1989) RCER(NRCER),(TABW(I1),I1=1,N)
      IF (LQTFP .EQ. 1) THEN
      WRITE(126,1988) RCER(NRCER),(TABW(I1),I1=1,N)
      WRITE(127,1988) RCER(NRCER),(TABW(I1),I1=1,N)
      ENDIF
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!~        DO 1984 I1=1,NHASKIND                   ! version matrice carre pour les QTF+
      DO 1984 I1=1,N                      ! version matrice antitriangulaire sup pour les QTF+ (0 ailleurs)
        
!!!!!!!!!!!!!! version matrice carre pour les QTF+!!!!!!!!!!!!!!!!!!!!!!
!~        !!!  QTFij-=QTFji-* !!!
!~        ! ON PREND LE CONJUGE DU TRIANGLE SUP
!~        WRITE(124,1991)TABW(I1),(REAL(EFFM(IJ,I1,I2,ICER)),I2=1,I1-1),0.,(REAL(EFFM(IJ,I2,I1,ICER)),I2=I1+1,NHASKIND)
!~        WRITE(125,1991)TABW(I1),(AIMAG(EFFM(IJ,I1,I2,ICER)),I2=1,I1-1),0.,(-AIMAG(EFFM(IJ,I2,I1,ICER)),I2=I1+1,NHASKIND)
!~        IF (LQTFP .EQ. 1) THEN
!~            !!!  QTFij+=QTFji+ !!!
!~            WRITE(126,1991)TABW(I1),(REAL(EFFP(IJ,I1,I2,ICER)),I2=1,I1-1),0.,(REAL(EFFP(IJ,I2,I1,ICER)),I2=I1+1,NHASKIND)
!~            WRITE(127,1991)TABW(I1),(AIMAG(EFFP(IJ,I1,I2,ICER)),I2=1,I1-1),0.,(AIMAG(EFFP(IJ,I2,I1,ICER)),I2=I1+1,NHASKIND)
!~        ENDIF
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

!!! version matrice antitriangulaire sup pour les QTF+ (0 ailleurs)!!!!!
      !!!  QTFij-=QTFji-* !!!
      ! ON PREND LE CONJUGE DU TRIANGLE SUP
      WRITE(124,1991)TABW(I1),(REAL(EFFM(IJ,I1,I2,NRCER)),I2=1,I1-1),0.,(REAL(EFFM(IJ,I2,I1,NRCER)),I2=I1+1,N)
      WRITE(125,1991)TABW(I1),(AIMAG(EFFM(IJ,I1,I2,NRCER)),I2=1,I1-1),0.,(-AIMAG(EFFM(IJ,I2,I1,NRCER)),I2=I1+1,N) 
      IF (LQTFP .EQ. 1) THEN
          !!!  QTFij+=QTFji+ !!!
          WRITE(126,1991)TABW(I1),(REAL(EFFP(IJ,I1,I2,NRCER)),I2=1,I1),(REAL(EFFP(IJ,I2,I1,NRCER)),I2=I1+1,N)
          WRITE(127,1991)TABW(I1),(AIMAG(EFFP(IJ,I1,I2,NRCER)),I2=1,I1),(AIMAG(EFFP(IJ,I2,I1,NRCER)),I2=I1+1,N) 
      ENDIF
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    1984 END DO
	WRITE(STRFMT,*)  "# FORMAT:",CHAR(10),				&
     & "# Rext     W2[1]    --- W2[j]    --- W2[N]",CHAR(10),		&
     & "# W1[1]    QTF[1,1] --- QTF[1,j] --- QTF[1,N]",CHAR(10),	&
     & "# .         .            .            .",CHAR(10),		&
     & "# .         .            .            .",CHAR(10),		&
     & "# .         .            .            .",CHAR(10),		&
     & "# W1[i]    QTF[i,1] --- QTF[i,j] --- QTF[i,N]",CHAR(10),	&
     & "# .         .            .            .",CHAR(10),		&
     & "# .         .            .            .",CHAR(10),		&
     & "# .         .            .            .",CHAR(10),		&
     & "# W1[N]    QTF[N,1] --- QTF[N,j] --- QTF[N,N]",CHAR(10),	&
     & "# Rext[2]   --- ",CHAR(10),					&
     & "#  . ",CHAR(10),						&
     & "#  . ",CHAR(10),						&
     & "#  . ",CHAR(10),CHAR(10)
     
	WRITE(124,*)STRFMT
	WRITE(125,*)STRFMT
	CLOSE(124)
	CLOSE(125)
	IF (LQTFP .EQ. 1) THEN
	    WRITE(126,*)STRFMT
	    WRITE(127,*)STRFMT
!!!! version matrice antitriangulaire sup pour les QTF+ (0 ailleurs) !!!!
	    WRITE(126,*) CHAR(10),CHAR(10),"# NB: Les valeurs des QTF+ pour w1+w2>n*dw sont definies a zeros.",CHAR(10),&
	    & "# en effet, un calcul de ces valeurs necessiterait un calcul d'ordre 1 sur 2 fois plus de pulsation."
	    WRITE(127,*) CHAR(10),CHAR(10),"# NB: Les valeurs des QTF+ pour w1+w2>n*dw sont definies a zeros.",CHAR(10),&
	    & "# en effet, un calcul de ces valeurs necessiterait un calcul d'ordre 1 sur 2 fois plus de pulsation."
	    
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	    CLOSE(126)
	    CLOSE(127)
	ENDIF
    ENDDO
1991 FORMAT(1F5.3,4000(3X,1E13.6))
1989 FORMAT(1F9.3,4000(1F13.3,3X))
1988 FORMAT(1F9.3,4000(1F13.3,3X))
1977 FORMAT('PULSATIONS : p1 =',I2,', p2 =',I2,', p- =',I2,', p+ =',I2,', RC =',1F4.0,1A)
END

            FUNCTION IL(NOM)
            CHARACTER(10) :: NOM
            IL=INDEX(NOM,' ')-1
            IF(IL < 0)IL=LEN(NOM)
            IF(IL == 0)THEN
                NOM='DEFAUT'
                IL=6
            ENDIF
            RETURN
            END
            FUNCTION X0(AK)
      IMPLICIT NONE
      REAL X0,XI,XM,XS,F
      REAL AK
      REAL T,APS,PAS
      INTEGER IITER,ITOUR
      F(T)=AK-T*TANH(T)
      APS=5.E-6
      ITOUR=0
      XI=0.
      XS=XI
      PAS=AMAX1(AK,SQRT(AK))
   30 XS=XS+PAS
      ITOUR=ITOUR+1
      IF(ITOUR.LE.1000)THEN
      IF(F(XS)*F(XI).GT.0)GOTO 30
      ENDIF
      IITER=0
   10 CONTINUE
      XM=(XI+XS)*0.5
      IITER=IITER+1
      IF(IITER.GT.1000.OR.ITOUR.GT.1000)THEN
      WRITE(*,110)ITOUR,IITER
  110 FORMAT(2X,'ERREUR DANS LA RECHERCHE DE LA RACINE',&
     &/2X,'APPROXIMATION =',I5,'   DICHOTOMIE = ',I5)
      STOP
      ELSE
      IF(ABS((XS-XI)/XM).GT.APS)THEN
      IF(F(XM)*F(XI).LT.0)THEN
      XS=XM
      ELSE
      XI=XM
      ENDIF
      GOTO 10
      ELSE
      X0=XM
      ENDIF
      ENDIF
      RETURN
      END
