      MODULE PARA
!---------------------------------------------------------------------
!
!  Module containing parameters for QTFSolver
!
!   NPT   : NOMBRE MAXIMUM DE SOMMETS DU MAILLAGE -> ATTENTION NPT DOIT
!           ETRE LE DOUBLE DE NFA ! 
!   NFA   : NOMBRE MAXIMUM DE FACETTES
!   NFB   : NOMBRE MAXIMUM DE FACETTES DU MAILLAGE ET DE
!                                SEGMENTS A LA FLOTTAISON
!   LN    : NOMBRE MAXIMUM DE CORPS
!   NI    : NOMBRE MAXIMUM D'ANGLES DE HOULE
!   LL,LE : BALISE POUR IMPORIMER SUR LE TERMINAL
!   NPIN  : NOMBRE MAXIMAL DE PULSATION ??
!   NFB   : NOMBRE MAXIMAL DE FACETTE DU CORPS ??
!   NFASL : NOMBRE MAXIMAL DE FACETTE SUR LA SURFACE LIBRE
!   NPASZ : ??
!   NEXR  : ?? 
!---------------------------------------------------------------------
      IMPLICIT NONE
      INTEGER,PARAMETER:: LL=5,LE=6,NPT=10000,NFA=5000,NFA2=5000
      INTEGER,PARAMETER:: NI=24,LN=8,NN=50,NPIN=201,NFB=5000
      INTEGER,PARAMETER:: NEXR=31,NFASL=500000,NPASZ=5000
      REAL,PARAMETER:: ERRE=1.E-06,PI=4*ATAN(1.),RADD=180./PI,G=9.806
      COMPLEX,PARAMETER:: ZI=(0.,1.)
      END MODULE PARA
